CMake: Add support for cygwin paths when using msvc
eclipse/omr pull request #4666
Opened 2019-12-11 21:01 UTC by dnakamura

Pass paths through cygpath when generating ddr files, so  that they will
be understood by msvc

Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

2020-02-11 21:38 UTC, dnakamura commented
@genie-omr build all

2020-09-01 17:30 UTC, dnakamura commented
@genie-omr build all

2020-09-03 21:00 UTC, keithc-ca requested changes

2020-09-08 16:56 UTC, dnakamura commented on cmake/modules/ddr/GenerateStub.cmake
> +	#input didnt have any ddr directives, so just dump an empty file
Artifact of an automated rebase

2020-09-08 17:06 UTC, dnakamura commented
@genie-omr build all

2020-09-08 17:35 UTC, keithc-ca commented on cmake/modules/ddr/GenerateStub.cmake
> +		if(_convert_rc)
For consistency, this should say `if(NOT _convert_rc EQUAL 0)` (see lines 50 & 59).

2020-09-14 19:00 UTC, youngar commented
@keithc-ca any more comments?

2020-09-14 19:44 UTC, keithc-ca approved these changes
I'm happy with the current state of this. I was trying to fix my Windows build environment to test it out before offering my final opinion, but I don't see a reason to hold this up any longer.

2020-09-14 21:46 UTC, youngar commented
@genie-omr build all

2020-09-15 04:41 UTC, merged