Add helper class for serialization of simple types
eclipse/omr pull request #5201
Opened 2020-05-15 21:58 UTC by ashu-mehra

Added TR_Serializer to help serialization and deserialization of
simple data types.
Also added code for (de-)serialization of TR_BitVector.

Signed-off-by: Ashutosh Mehra <mehra.ashutosh@ibm.com>

2020-05-15 22:01 UTC, ashu-mehra commented
Changes in this PR are to support serialization of `TR_PersistentProfieInfo` in OpenJ9.
The OpenJ9 PR dependent on this is https://github.com/eclipse/openj9/pull/9590

2020-05-19 12:21 UTC, 0xdaryl commented
Could you add some Doxygen comments to this new class please?

2020-05-19 13:13 UTC, andrewcraik commented
Is there a design for how this should work at a high level explaining the API design choices? I think this would be valuable to facilitate review and for those looking to utilize this infrastructure in the future.

2020-08-19 19:19 UTC, vijaysun-omr commented
Ping to see if this can be moved forward in the next few days

2020-08-20 11:33 UTC, vijaysun-omr commented
@andrewcraik some new changes including comments to facilitate review have been added. So this may be ready for your review again.

2020-10-05 12:57 UTC, vijaysun-omr commented
@andrewcraik or @ashu-mehra any update on this ?

2020-10-15 21:24 UTC, andrewcraik commented
The details are a bit more clear - what is the purpose of this and how is it going to be used?

2020-11-04 16:39 UTC, ashu-mehra commented
> The details are a bit more clear - what is the purpose of this and how is it going to be used?

I have created a design https://github.com/eclipse/openj9/issues/9974 for all the related changes which also shows how the `TR_Serializer` class can be used.

2020-11-05 17:01 UTC, vijaysun-omr commented
@dsouzai fyi and @andrewcraik a ping to review the design document that was linked.

2020-11-10 19:29 UTC, dsouzai requested changes
Overall looks ok; suggested a couple of changes, and had a couple of questions regarding the support of the c++ features used.

2020-11-10 19:29 UTC, dsouzai commented on compiler/infra/Serializer.hpp
> +      static_assert(std::is_trivially_copyable<T>::value, "Cannot determine size of non-trivially copyable types");
is `is_trivially_copyable` supported on all compiler version? I imagine with the move to the newer version of GCC and MSVC, those are probably fine, but not sure about XLC considering it was introduced in c++11.

2020-11-10 19:29 UTC, dsouzai commented on compiler/infra/Serializer.hpp
> +   template<typename T, typename... Args>
Same point as above about variadic templates; it's listed as unsupported in [1] but it states MSVC, so maybe it's not a problem on XLC?

[1] https://github.com/eclipse/omr/blob/master/doc/SupportedC%2B%2BFeatures.md#minimum-compiler-support

2020-11-10 19:29 UTC, dsouzai commented on compiler/infra/Serializer.hpp
> + * Copyright (c) 2000, 2019 IBM Corp. and others
Copyright.

2020-11-10 19:29 UTC, dsouzai commented on compiler/infra/Serializer.hpp
> +	 }
formatting

2020-11-10 19:29 UTC, dsouzai commented on compiler/infra/BitVector.hpp
> +      _numChunks = serializer.read<int32_t>();
perhaps you should use the multi param version of `read` to ensure that the order in which these fields are read does not change.

2020-11-12 20:50 UTC, Leonardo2718 requested changes
A few initial comments:

- Is this really something that the OMR project needs? The link to the OpenJ9 issues shows how this class is inteneded to be used in OpenJ9, but an explenation of the benifit this class brings to OMR is still needed. Also, if this class is to live in OMR, then the documentation explaining how it works and how to use should as well.
- If this is something the OMR project needs, why not use an exisiting C++ serialization framework (e.g. Boost Serialization)?
- If there is a reason for OMR to have its own serialization utility, then can it be made accessable/usable by other OMR components and not just the compiler?
- It looks to me like this new class is really providing three things: serialization, deserialization, and some utilities to help calculate the size of the buffer needed to serialize some data. Each of these should really be a separate class.
- We're going to need unit tests for these new utilities.

2020-11-13 16:01 UTC, ashu-mehra commented
> Is this really something that the OMR project needs? The link to the OpenJ9 issues shows how this class is inteneded to be 
> used in OpenJ9, but an explenation of the benifit this class brings to OMR is still needed. Also, if this class is to live in OMR, then the documentation explaining how it works and how to use should as well.

It depends on the data structures we are trying to serialize. For this particular case I need to serialize `TR_BitVector` which resides in OMR. It is possible we may need to serialize other data structures as well, but as of now TR_BitVector is the only one from OMR, rest are in OpenJ9.

> If this is something the OMR project needs, why not use an exisiting C++ serialization framework (e.g. Boost Serialization)?
> If there is a reason for OMR to have its own serialization utility, then can it be made accessable/usable by other OMR components and not just the compiler?

Requirement is not from OMR project as such, but from OpenJ9. AFAIK there isn't any widespread use of serialization in the project, so I am not sure it would be a good idea to add dependency on boost library.
Others more familiar with the project code base may know better if we need OMR to have its own serialization utility. If that's the case then I agree looking at the boost framework should be the first step.

I can understand the concerns around the utility of this class for OMR project given a very narrow use-case in the project. It was only meant to be used as a helper class to avoid boiler plate code involved in reading and writing data to memory buffer. I can instead move the functionality to `TR_BitVector::serialize()` and `TR_BitVector::deserialize()` methods and get rid of the helper class completely.

2020-11-30 15:27 UTC, ashu-mehra commented
@Leonardo2718 @dsouzai I have removed `TR_Serializer` from the change set. New changes only perform serialization of `TR_BitVector` as required by https://github.com/eclipse/openj9/pull/9590.
Removing `TR_Serializer` should address many of the concerns raised during the review.

2020-11-30 15:31 UTC, ashu-mehra commented
This PR's main purpose was to introduce `TR_Serializer`, but now that it has been removed and is only performing (de-)serialization of `TR_BitVector`, it would be better to close this PR and open a new one.

2020-11-30 15:31 UTC, closed without merging

2020-11-30 15:39 UTC, ashu-mehra commented
I have opened https://github.com/eclipse/omr/pull/5693 which just performs (de-)serialization of `TR_BitVector`.