Fix build break on PPC-32
eclipse/omr pull request #5534
Opened 2020-09-08 18:36 UTC by zl-wang

The NULL pointer needs to be casted to (TR::Register *), otherwise it could match with an int parameter.
Thus, multiple matching for the OMRMemoryReference constructors.

Signed-off-by: Julian Wang <zlwang@ca.ibm.com>

2020-09-08 18:53 UTC, fjeremic commented on compiler/p/codegen/OMRMemoryReference.cpp
> +            TR::MemoryReference *fakeTocRef = new (cg->trHeapMemory()) TR::MemoryReference((TR::Register *)NULL, 0, sizeof(uintptr_t), cg);
```suggestion
            TR::MemoryReference *fakeTocRef = new (cg->trHeapMemory()) TR::MemoryReference(static_cast<TR::Register *>(NULL), 0, sizeof(uintptr_t), cg);
```

2020-09-08 18:54 UTC, aviansie-ben requested changes
Your explanation here does not make sense to me. There are no `MemoryReference` constructor overloads where the first parameter is an int, so I don't see any way that `NULL` being convertible to int could possibly cause issues in the way you've described. Can you please clarify what the problem you're fixing here is?

2020-09-08 19:07 UTC, zl-wang commented
Build error messages:
"../omr/compiler/p/codegen/OMRMemoryReference.cpp", line 1639.47: 1540-0219 (S) The call to "MemoryReference::MemoryReference" has no best match.
"../omr/compiler/p/codegen/OMRMemoryReference.cpp", line 1639.92: 1540-1229 (I) Argument number 1 is an rvalue of type "int".
"../omr/compiler/p/codegen/OMRMemoryReference.cpp", line 1639.98: 1540-1229 (I) Argument number 2 is an rvalue of type "int".
"../omr/compiler/p/codegen/OMRMemoryReference.cpp", line 1639.101: 1540-1229 (I) Argument number 3 is an rvalue of type "unsigned int".
"../omr/compiler/p/codegen/OMRMemoryReference.cpp", line 1639.120: 1540-1228 (I) Argument number 4 is an lvalue of type "TR::CodeGenerator *".
"../omr/compiler/p/codegen/MemoryReference.hpp", line 71.4: 1540-1202 (I) No candidate is better than "TR::MemoryReference::MemoryReference(TR::Node *, TR::SymbolReference *, uint32_t, TR::CodeGenerator *)".
"../omr/compiler/p/codegen/OMRMemoryReference.cpp", line 1639.92: 1540-1231 (I) The conversion from argument number 1 to "TR::Node *" uses "a pointer conversion".
"../omr/compiler/p/codegen/OMRMemoryReference.cpp", line 1639.98: 1540-1231 (I) The conversion from argument number 2 to "TR::SymbolReference *" uses "a pointer conversion".
"../omr/compiler/p/codegen/OMRMemoryReference.cpp", line 1639.101: 1540-1231 (I) The conversion from argument number 3 to "unsigned int" uses "the identity conversion".
"../omr/compiler/p/codegen/OMRMemoryReference.cpp", line 1639.120: 1540-1231 (I) The conversion from argument number 4 to "TR::CodeGenerator *" uses "an lvalue-to-rvalue transformation".
"../omr/compiler/p/codegen/MemoryReference.hpp", line 62.4: 1540-1202 (I) No candidate is better than "TR::MemoryReference::MemoryReference(TR::Register *, int32_t, uint8_t, TR::CodeGenerator *)".
"../omr/compiler/p/codegen/OMRMemoryReference.cpp", line 1639.92: 1540-1231 (I) The conversion from argument number 1 to "TR::Register *" uses "a pointer conversion".
"../omr/compiler/p/codegen/OMRMemoryReference.cpp", line 1639.98: 1540-1231 (I) The conversion from argument number 2 to "int" uses "the identity conversion".
"../omr/compiler/p/codegen/OMRMemoryReference.cpp", line 1639.101: 1540-1231 (I) The conversion from argument number 3 to "unsigned char" uses "an integral conversion".
"../omr/compiler/p/codegen/OMRMemoryReference.cpp", line 1639.120: 1540-1231 (I) The conversion from argument number 4 to "TR::CodeGenerator *" uses "an lvalue-to-rvalue transformation".

2020-09-08 19:11 UTC, zl-wang commented on compiler/p/codegen/OMRMemoryReference.cpp
> +            TR::MemoryReference *fakeTocRef = new (cg->trHeapMemory()) TR::MemoryReference((TR::Register *)NULL, 0, sizeof(uintptr_t), cg);
done

2020-09-08 19:12 UTC, zl-wang commented
Build error messages:
"../omr/compiler/p/codegen/OMRMemoryReference.cpp", line 1639.47: 1540-0219 (S) The call to "MemoryReference::MemoryReference" has no best match.
"../omr/compiler/p/codegen/OMRMemoryReference.cpp", line 1639.92: 1540-1229 (I) Argument number 1 is an rvalue of type "int".
"../omr/compiler/p/codegen/OMRMemoryReference.cpp", line 1639.98: 1540-1229 (I) Argument number 2 is an rvalue of type "int".
"../omr/compiler/p/codegen/OMRMemoryReference.cpp", line 1639.101: 1540-1229 (I) Argument number 3 is an rvalue of type "unsigned int".
"../omr/compiler/p/codegen/OMRMemoryReference.cpp", line 1639.120: 1540-1228 (I) Argument number 4 is an lvalue of type "TR::CodeGenerator *".
"../omr/compiler/p/codegen/MemoryReference.hpp", line 71.4: 1540-1202 (I) No candidate is better than "TR::MemoryReference::MemoryReference(TR::Node *, TR::SymbolReference *, uint32_t, TR::CodeGenerator *)".
"../omr/compiler/p/codegen/OMRMemoryReference.cpp", line 1639.92: 1540-1231 (I) The conversion from argument number 1 to "TR::Node *" uses "a pointer conversion".
"../omr/compiler/p/codegen/OMRMemoryReference.cpp", line 1639.98: 1540-1231 (I) The conversion from argument number 2 to "TR::SymbolReference *" uses "a pointer conversion".
"../omr/compiler/p/codegen/OMRMemoryReference.cpp", line 1639.101: 1540-1231 (I) The conversion from argument number 3 to "unsigned int" uses "the identity conversion".
"../omr/compiler/p/codegen/OMRMemoryReference.cpp", line 1639.120: 1540-1231 (I) The conversion from argument number 4 to "TR::CodeGenerator *" uses "an lvalue-to-rvalue transformation".
"../omr/compiler/p/codegen/MemoryReference.hpp", line 62.4: 1540-1202 (I) No candidate is better than "TR::MemoryReference::MemoryReference(TR::Register *, int32_t, uint8_t, TR::CodeGenerator *)".
"../omr/compiler/p/codegen/OMRMemoryReference.cpp", line 1639.92: 1540-1231 (I) The conversion from argument number 1 to "TR::Register *" uses "a pointer conversion".
"../omr/compiler/p/codegen/OMRMemoryReference.cpp", line 1639.98: 1540-1231 (I) The conversion from argument number 2 to "int" uses "the identity conversion".
"../omr/compiler/p/codegen/OMRMemoryReference.cpp", line 1639.101: 1540-1231 (I) The conversion from argument number 3 to "unsigned char" uses "an integral conversion".
"../omr/compiler/p/codegen/OMRMemoryReference.cpp", line 1639.120: 1540-1231 (I) The conversion from argument number 4 to "TR::CodeGenerator *" uses "an lvalue-to-rvalue transformation".

2020-09-08 19:28 UTC, aviansie-ben commented
From the error message, it looks like the actual problem is that the `NULL` is ambiguous between `TR::Register*` and `TR::Node*`. The following 0 could then be interpreted either as an `int` or as a `TR::SymbolReference*`. Normally, this would prefer the interpretation as an `int`, but the fact that the following argument differs between the two overloads (one has an `unsigned int` len and one has an `unsigned char` len) and one of these just happens to match exactly on ppc32 causes the ambiguity to be unresolvable. Does anyone happen to know what the reason is that these two overloads use different types for their lengths? If this were not the case, the ambiguity would resolve correctly.

All that being said, I'd really prefer that we move to using static factory methods for constructing memory references (see #5172). With that approach, this sort of ambiguity could be resolved by naming the static factory methods differently rather than simply relying on the (often confusing) overload resolution rules to pick one of the constructors. IIUC, @midronij is currently working on that, so perhaps this could be resolved that way instead of adding yet another hacky fix to the pile?

2020-09-09 12:27 UTC, zl-wang commented
It had better let #5172 run the course.

2020-09-09 16:01 UTC, aviansie-ben commented
@zl-wang Sorry, I don't quite understand your last message. Can you please clarify whether you agree that we should wait for work on #5172 to be completed instead and thus that this PR should be closed?

2020-09-09 16:07 UTC, zl-wang commented
No, this fix should be merged, while #5172 took the time to finish.

2020-09-09 16:19 UTC, aviansie-ben requested changes
In that case, at the very least I'd like to see the commit message here updated to fix the incorrect description of the issue being solved and to have a more descriptive subject line that actually reflects what's being fixed, e.g. "Fix ambiguous constructor call on ppc32".

2020-09-09 19:11 UTC, aviansie-ben approved these changes

2020-09-09 19:11 UTC, aviansie-ben commented
@genie-omr build plinux,aix

2020-09-10 13:20 UTC, aviansie-ben commented
After I approved this PR but before I had the chance to merge it, it seems that @midronij opened #5536 which switches to using static factory methods and thus makes this fix obsolete. I'm going to try to get that PR in instead of this one, but I'll keep this PR open for the time being in case something comes up that prevents the other PR from being merged in a timely manner.

2020-09-10 14:08 UTC, fjeremic approved these changes

2020-09-11 18:59 UTC, aviansie-ben commented
Since #5536 has now been merged, the build break should be corrected and this PR should no longer be needed.

@zl-wang Can you confirm that the issue is resolved now? If so, this PR can be closed.

2020-09-14 12:33 UTC, zl-wang commented
the latest 32bit build was still on the "old" file.  but close this anyway.

2020-09-14 14:22 UTC, closed without merging