Provide Factory Methods for Power MemoryReference objects
eclipse/omr pull request #5536
Opened 2020-09-09 20:49 UTC by midronij

This PR does the following:

-Add static helper methods for each MemoryReference constructor
-Replace all direct calls to MemoryReference constructors with corresponding static helpers
-Remove and replace legacy MemoryReference constructor
-Change all MemoryReference constructors from public to private/protected

2020-09-09 21:23 UTC, aviansie-ben reviewed
Just a quick comment before I start a full review: it looks like these changes are structured in such a way that they'll require a coordinated merge between OMR and OpenJ9. Perhaps this can be split into 2 PRs, with one to add the new static factory methods and switch OMR to use them and another to remove/privatize the old constructors and remove the int parameter hack? That should hopefully allow us to avoid needing a coordinated merge.

Barring that, somebody else will need to be the committer to merge this PR, as I'm not a committer at OpenJ9 and thus can't handle a coordinated merge between the two projects on my own.

2020-09-09 21:27 UTC, midronij commented
@aviansie-ben I'll try splitting this PR in two to simplify the merging process

2020-09-10 02:04 UTC, aviansie-ben requested changes
Please rewrite the commit message subject line on the 2nd commit (e9d9f3f8fea8215c636a94d234f7266e1134d15b) to use the imperative mood (i.e. don't use past tense) per the [contribution guidelines](https://github.com/eclipse/omr/blob/master/CONTRIBUTING.md#commit-guidelines).

I see that a couple of changes in `OMRTreeEvaluator.cpp` seem to have escaped into #5537, which should be moved back into this PR. I can also still see some calls to the `TR::MemoryReference` constructors in the compiler unit tests that need to be updated.

2020-09-11 12:29 UTC, aviansie-ben requested changes

2020-09-11 12:29 UTC, aviansie-ben commented on compiler/p/codegen/PPCSystemLinkage.cpp
> +         //NOTE (remove this comment later): the fact that the displacement here is negative might mess things up when displacement is changed from 32 bits to 64 bits
This comment is identical to one I pointed out in my previous review and should also be removed.

2020-09-11 17:15 UTC, aviansie-ben approved these changes

2020-09-11 17:16 UTC, aviansie-ben commented
@genie-omr build plinux,aix

2020-09-11 17:31 UTC, aviansie-ben commented
Looks like the compiler unit tests are failing to build with this change:

```
[2020-09-11T17:22:08.627Z] In file included from /home/jenkins/workspace/Build/fvtest/compilerunittest/p/Peephole.cpp:23:0:
[2020-09-11T17:22:08.628Z] /home/jenkins/workspace/Build/fvtest/compilerunittest/p/Util.hpp: In member function ‘TR::MemoryReference* MemoryReference::reify(TR::CodeGenerator*) const’:
[2020-09-11T17:22:08.628Z] /home/jenkins/workspace/Build/fvtest/compilerunittest/p/Util.hpp:94:13: error: expected primary-expression before ‘)’ token
[2020-09-11T17:22:08.628Z]              );
```

2020-09-11 18:34 UTC, aviansie-ben commented
@genie-omr build plinux,aix

2020-09-11 18:58 UTC, aviansie-ben commented
Not waiting for Travis since this is a Power-specific change

2020-09-11 18:58 UTC, merged