Support Long Type Length Node within setmemoryEvaluator
eclipse/omr pull request #5590
Opened 2020-10-01 15:03 UTC by AlenBadel

The evaluator generates a sequence of instructions that initializes a segment of memory of a specified length with a specified value. 

Currently, the evaluator does not support length Nodes of type Long. This commit enables such support, while maintaining support for Integer types.

Signed-off-by: AlenBadel <Alen.Badel@ibm.com>

2020-10-01 17:03 UTC, gita-omr reviewed
Is this the only place lengthReg is used?

2020-10-01 17:27 UTC, AlenBadel commented
> Is this the only place lengthReg is used?

No, it is also used to compare and branch into residuals which handle remnant sizes including 16/8/4/2/1 byte setting.

2020-10-01 18:19 UTC, AlenBadel commented
> We need to check if Long type is handled properly in those cases as well.

Yes, all of the instructions that later on use the long length register, or any register the value is transferred to looks like they are 64bit compatible instructions.

2020-10-01 18:35 UTC, gita-omr commented
> Yes, all of the instructions that later on use the long length register, or any register the value is transferred to looks like they are 64bit compatible instructions.

Op_cmpli is compatible with Long type by luck. Strictly speaking it's not compatible with Int type. I think would be nice to have a similar check on the node type and generate either cmpli4 or cmpli8.

2020-10-01 19:42 UTC, aviansie-ben requested changes
From a quick examination, it looks like this code is only being used to implement OpenJ9's `Unsafe.setMemory` recognized method. Can anybody shed light on why this isn't just implemented using `arrayset` instead? At the very least, if we do need two separate implementations for some reason, I don't think this should be in OMR. I do admit that these questions might be beyond the scope of this particular PR though, so I can probably still let this PR through and open an issue to resolve those questions.

Aside from that, it looks like the message on your second commit is missing the `Signed-off-by` footer, causing the ECA check to fail. Please squash these commits and ensure that the resulting commit has the correct `Signed-off-by` footer.

2020-10-01 20:03 UTC, AlenBadel commented
>  Can anybody shed light on why this isn't just implemented using `arrayset` instead?

I don't see any reason why it can't. The `arraysetEvaluator` would just to be changed to support Long type length nodes. Very similar changes to what we see here.

Commits have been squashed.

2020-10-01 20:06 UTC, aviansie-ben requested changes
Sorry, missed this in my earlier review but I just realized that your commit message doesn't meet our [guidelines](https://github.com/eclipse/omr/blob/master/CONTRIBUTING.md#commit-guidelines). Specifically, please make sure that the body of the commit message is wrapped at 72 characters and please use the OMR names when referring to types rather than the Java names (Long -> Int64, Integer -> Int32).

2020-10-01 20:22 UTC, AlenBadel commented
Thanks. Commit has been changed.

2020-10-01 20:42 UTC, aviansie-ben commented
> I don't see any reason why it can't. The `arraysetEvaluator` would just to be changed to support Long type length nodes. Very similar changes to what we see here.

I've opened eclipse/openj9#10765 for further discussion and tracking of this at OpenJ9 in the interests of allowing this PR to proceed.

> Thanks. Commit has been changed.

The new commit message's body seems to be completely different from before. It's missing information from the previous version and seems to be wrapped long before 72 characters for seemingly no reason.

2020-10-01 21:22 UTC, AlenBadel commented
> The new commit message's body seems to be completely different from before. It's missing information from the previous version and seems to be wrapped long before 72 characters for seemingly no reason.

My fault, I attempted to simplify the commit message. This should be in accordance with the guidelines now.

2020-10-02 00:31 UTC, gita-omr approved these changes
The code changes look good to me. Thanks!

2020-10-02 13:15 UTC, aviansie-ben approved these changes

2020-10-02 13:15 UTC, aviansie-ben commented
@genie-omr build plinux,aix

2020-10-02 13:48 UTC, merged