WIP: Rename codeGen to cg
eclipse/omr pull request #5608
Opened 2020-10-14 13:24 UTC by pkrc267

This patch makes naming of CodeGenerator variable consistent by replacing all occurances of 

> codeGen

 with 

> cg

 which is more popular.

Issue: #5594
Signed-off-by: Prakhar Yadav <pkrc267@gmail.com>

2020-10-14 16:50 UTC, 0xdaryl requested changes
I suspect your editor (or some other means) is reformatting the source code on the files you changed.  Please try and keep as much of the original source code formatting in place.

2020-10-14 16:50 UTC, fjeremic commented
@pkrc267 welcome to the project. Thanks for your contribution. There seems to be quite a bit of whitespace changes in this PR which makes it very difficult to properly review. It looks like you make have used some sort of auto-formatting tool on the files changed which changed many more lines. Could I suggest we remove the whitespace changes and formatting changes so we can isolate the "meat" of this change, which is to rename "codeGen" to "cg"?

2020-10-14 16:59 UTC, pkrc267 commented
@fjeremic  Alright. I'll go ahead and create a new brach. This time make changes that only takes care of renaming. I used VS Code and maybe that caused the unwanted changes. I'll do it manually this time.

2020-10-14 17:01 UTC, fjeremic commented
> @fjeremic Alright. I'll go ahead and create a new brach. This time make changes that only takes care of renaming. I used VS Code and maybe that caused the unwanted changes. I'll do it manually this time.

Thanks. No need to create a new branch and new PR. You can just force push to your existing `codeGen-renaming` branch and this PR will automatically get updated.

2020-10-14 17:07 UTC, pkrc267 commented
> > @fjeremic Alright. I'll go ahead and create a new brach. This time make changes that only takes care of renaming. I used VS Code and maybe that caused the unwanted changes. I'll do it manually this time.
> 
> Thanks. No need to create a new branch and new PR. You can just force push to your existing `codeGen-renaming` branch and this PR will automatically get updated.

😀 okay. Thanks. I'll do that.

2020-10-16 14:52 UTC, 0xdaryl reviewed
I'm going to run CI just to see if there are build issues.

2020-10-16 14:52 UTC, 0xdaryl commented on compiler/aarch64/codegen/ARM64SystemLinkage.cpp
> +   TR::CodeGenerator *cg = cg();
This will likely be a problem with the name shadowing.  You might need to say `this->cg()`.

2020-10-16 14:52 UTC, 0xdaryl commented
@genie-omr build all

2020-10-16 14:58 UTC, 0xdaryl commented
You may need to resolve the merge conflicts before CI can run.

2020-10-16 15:23 UTC, pkrc267 commented
How do I resolve the conflict. The conflict is in files: `compiler/codegen/Relocation.cpp` & `compiler/codegen/Relocation.hpp`
Please help @0xdaryl

2020-10-16 15:38 UTC, 0xdaryl commented
> How do I resolve the conflict.

I suggest you rebase your commit on top of the latest OMR `master` branch.  When you do so, git will tell you that you have a merge conflict on those two files and abort the rebase so that you can make the necessary changes (git will provide instructions on-screen for how to proceed).

2020-10-16 15:40 UTC, 0xdaryl commented
If you have never done this before, perhaps this resource will be helpful:  https://github.com/eclipse/omr/blob/master/doc/GitCrashCourse.md

2020-10-19 20:34 UTC, pkrc267 commented
@0xdaryl I'm getting 3 errors in Build. Please help me fix it.

2020-10-19 20:59 UTC, 0xdaryl commented
Your build failures are occurring because you deleted Relocation.cpp/Relocation.hpp.

Something went awry with your rebase as you now have 18 commits.  You should probably only have 1 commit if your rebase went cleanly.  I'm not sure what methodology you're following to rebase, but I suggest you try again starting with your lone commit in this PR.  Did you have a look at the "rebasing" section in our Git Crash Course document?

2020-10-19 21:47 UTC, pkrc267 commented
Oh yes I looked at it and thought I should have resolved the issue with those 2 files manually. (Instead deleted them. Mistake. Learned from it)

The 18 commits however is a separate mistake that I did. I was trying to update my forked repository(pkrc267/omr) and local repository with the latest **omr** repo. And somehow I made commit to the eclipse/omr. Which wasn't my intention.
Sorry for the mess 🤐

2020-10-20 18:02 UTC, pkrc267 commented
@0xdaryl I think I have messed this PR real bad. Can we retry this and start fresh? Is there a way to remove this PR so that I can start a new one, such that we can have just 1 commit that solves the issue?

2020-10-21 00:13 UTC, 0xdaryl commented
There may be cleaner ways to do it, but I suppose you could close this PR, create a new branch based on the most up-to-date OMR `master` branch, cherry-pick your rename commit onto it (i.e., `git cherry-pick <your commit SHA>`), and then create a new PR from that new branch.

Given the nature of these changes, I expect that you should only have one commit to contribute.

2020-11-03 14:21 UTC, 0xdaryl commented
Hi @pkrc267...  Are you still planning on making progress on this one, or should it be closed while you sort out the rebasing issues?

2020-11-03 14:41 UTC, pkrc267 commented
I think it's better to close this PR. I wish to open a new PR in which I'll make the required changes in clean manner.

2020-11-03 15:06 UTC, 0xdaryl commented
Thanks.  I will close this now.  Please reach out again if you need assistance.

2020-11-03 15:06 UTC, closed without merging