WIP: Rename codeGen to cg
eclipse/omr pull request #5661
Opened 2020-11-07 04:40 UTC by pkrc267

This patch makes all instances of CodeGenerator variables from `codeGen` to `cg`.

Issue: #5594
Signed-off-by: Prakhar Yadav <pkrc267@gmail.com>

2020-11-08 06:32 UTC, pkrc267 commented
@0xdaryl 2 tests are failing for x86-64 macOS. Can you please guide me in fixing them! These are the ones:
```
31: [  FAILED  ] 2 tests, listed below:
31: [  FAILED  ] PortSockTest.poll_functionality_basic
31: [  FAILED  ] PortSockTest.poll_functionality_many_sockets
```

2020-11-08 16:11 UTC, fjeremic commented
> @0xdaryl 2 tests are failing for x86-64 macOS.

I believe those are due to #5581. They shouldn't be related to this change.

2020-11-09 04:24 UTC, pkrc267 commented
Okay, thanks for clarifying. So how to proceed from here?

2020-11-09 13:15 UTC, 0xdaryl requested changes
This change generally looks good.  Thanks for contributing.

You should sweep through this PR and find all patterns like this `cg = cg()` as they will fail to compile (depending on the context you should probably replace this with `cg = this->cg()`.  I highlighted a few places where this needs to be changed in this PR, but  I might have missed some so please review.

I won't launch a genie build until those places are fixed because I know it will fail.

This PR should also be squashed into a single commit.  Perhaps once you fix the `cg = this->cg()` issue you can squash before pushing.  I will then launch a genie build on that.

2020-11-09 13:15 UTC, 0xdaryl commented on compiler/riscv/codegen/RVSystemLinkage.cpp
> +   TR::CodeGenerator *cg = cg();
This will need to be `this->cg()`

2020-11-09 13:15 UTC, 0xdaryl commented on compiler/riscv/codegen/RVSystemLinkage.cpp
> +   TR::CodeGenerator *cg = cg();
This will need to be `this->cg()`

2020-11-09 13:15 UTC, 0xdaryl commented on compiler/aarch64/codegen/ARM64SystemLinkage.cpp
> +   TR::CodeGenerator *cg = cg();
The compiler can't determine if `cg` refers to the function or the auto, so you need to introduce a `this->cg()` to remove the ambiguity.  This happens in a number of places throughout this PR.

2020-11-09 13:15 UTC, 0xdaryl commented on compiler/arm/codegen/ARMSystemLinkage.cpp
> +   TR::CodeGenerator *cg = cg();
`this->cg()`

2020-11-09 13:15 UTC, 0xdaryl commented on compiler/arm/codegen/ARMSystemLinkage.cpp
> +   TR::CodeGenerator *cg = cg();
`this->cg()`

2020-11-09 19:33 UTC, 0xdaryl commented
@genie-omr build all

2020-11-09 21:12 UTC, 0xdaryl commented
Please address compilation failures in the CI builds.  Looks like a couple of cg/cg() instances were missed on the ARM/AArch64 platforms.

2021-02-01 14:47 UTC, 0xdaryl commented
Are you still planning on making progress with this PR?  If not in the near term, may I suggest you close this PR while you work on addressing the issues in your private fork, and then open a PR again when the changes are ready for review.  Thanks.

2021-02-04 16:33 UTC, 0xdaryl commented
I am closing this as stale as the last two inquiries have gone unanswered.  If you make further progress in your private fork and wish to contribute it please feel free to open a PR again in the future.  Thanks for the contribution.

2021-02-04 16:33 UTC, closed without merging