Add preProcess stage to recognized call transformer
eclipse/omr pull request #5694
Opened 2020-11-30 21:51 UTC by liqunl

Some transformation require additional data or the trees to be
preprocessed, so add a preProcess extention point to be implemented by
downstream projets.

Also dump trees before and after the transformation when trace is on.

Signed-off-by: Liqun Liu <liqunl@ca.ibm.com>

2020-11-30 21:52 UTC, liqunl commented
@0xdaryl May I have a review? This is needed by https://github.com/eclipse/openj9/pull/11309

2020-12-02 13:06 UTC, 0xdaryl commented
@genie-omr build all

2020-12-02 13:08 UTC, 0xdaryl requested changes
I am fine with the code changes.  Just a couple of minor typos in the commit message to fix up please:
* extention -> extension
* projet -> project

2020-12-02 13:58 UTC, 0xdaryl commented
Please see CI build failure.

2020-12-07 16:37 UTC, 0xdaryl commented
@genie-omr build all

2020-12-07 17:47 UTC, 0xdaryl approved these changes

2020-12-07 17:47 UTC, merged