RISC-V: assorted changes for OpenJ9 JIT
eclipse/omr pull request #5699
Opened 2020-12-02 12:32 UTC by janvrany

This PR adds a few changes here and there required by OpenJ9 JIT component

2020-12-02 14:05 UTC, 0xdaryl requested changes
Just a comment for this PR and any future ones you may be making as you go about implementing an OpenJ9 JIT for RISC-V.  If a commit is truly language-agnostic (ideally they should all be :-) ) and benefits all consumers of OMR then you don't need to call out OpenJ9 in your commit message unless it is particularly relevant.

For example, in the commit message for c4b591253b642135ba3ce22307aeb52120e323b6  you don't need to reference OpenJ9 as an example.

2020-12-04 20:31 UTC, janvrany commented on compiler/riscv/codegen/OMRLinkage.cpp
> +   }
Fixed in  90b02e8

2020-12-04 20:39 UTC, janvrany commented on compiler/env/Processors.hpp
> +   TR_RV645G,
Good catch! It is not, it's a typo followed by copy-paste. Fixed in a24d33e. 
Actually, I was thinking of aligning this too: 
https://github.com/eclipse/omr/blob/5080dab1ef5fe56e8773ae1655ff98375d7e84ac/include_core/omrport.h#L1410-L1415
and use (only) `OMR_PROCESOR_RV64G` (RV32G is not supported yet anyway)

2020-12-06 23:45 UTC, 0xdaryl commented
@genie-omr build aarch64

2020-12-07 12:47 UTC, 0xdaryl approved these changes

2020-12-07 12:47 UTC, merged