RISC-V: implement helper call snippet
eclipse/omr pull request #5740
Opened 2021-01-07 10:51 UTC by janvrany

2021-01-28 20:57 UTC, 0xdaryl requested changes
Generally looks good.  Minor suggestions only.

2021-01-28 20:57 UTC, 0xdaryl commented on compiler/riscv/codegen/RVHelperCallSnippet.cpp
> +         TR_ASSERT(false, "Target too far away.  Not supported yet");
You should make this a `TR_ASSERT_FATAL`

2021-01-28 20:57 UTC, 0xdaryl commented on compiler/riscv/codegen/RVHelperCallSnippet.cpp
> +         TR_ASSERT(false, "Target too far away.  Not supported yet");
You should make this a `TR_ASSERT_FATAL`

2021-01-28 20:57 UTC, 0xdaryl commented on compiler/riscv/codegen/RVHelperCallSnippet.cpp
> +      TR_ASSERT(VALID_UJTYPE_IMM(distance), "Trampoline too far away.");
`TR_ASSERT_FATAL`

2021-01-28 20:57 UTC, 0xdaryl commented on compiler/riscv/codegen/RVHelperCallSnippet.cpp
> +      TR_ASSERT(VALID_UJTYPE_IMM(distance), "Trampoline too far away.");
`TR_ASSERT_FATAL`

2021-01-28 20:57 UTC, 0xdaryl commented on compiler/riscv/CMakeLists.txt
> +        ${CMAKE_CURRENT_LIST_DIR}/codegen/RVHelperCallSnippet.cpp
Fix indenting please.

2021-01-29 06:36 UTC, janvrany commented
Everything mentioned is addressed in 3dab8a0.

2021-01-29 12:53 UTC, 0xdaryl approved these changes

2021-01-29 12:53 UTC, merged