Eliminate vm.heapBaseAddress()
eclipse/omr pull request #5757
Opened 2021-01-19 15:57 UTC by dchopra001

Signed-off-by: Dhruv Chopra <Dhruv.C.Chopra@ibm.com>

2021-01-19 19:30 UTC, Leonardo2718 commented
What's the reason for doing this? The commit message doesn't have a description.

2021-01-19 19:33 UTC, dchopra001 commented
> What's the reason for doing this? The commit message doesn't have a description.

Sorry about that I've updated it now.

2021-01-19 21:38 UTC, fjeremic requested changes

2021-01-19 21:38 UTC, fjeremic commented on compiler/optimizer/GlobalRegisterAllocator.cpp
> -         changeHeapBaseConstToLoad(comp(), autoSymRef, tt->getNode(), visitCount);
As far as I can see if you eliminate the call to `changeHeapBaseConstToLoad` here then this function is dead. Can we remove it?

2021-01-19 21:38 UTC, fjeremic commented on compiler/z/codegen/OMRTreeEvaluator.cpp
>              translatedNode = translatedNode->getFirstChild();
This code involving `translatedNode` seems to have no use. Can we remove it? Similarly in the other codegens.

2021-01-21 16:00 UTC, fjeremic approved these changes

2021-01-21 16:00 UTC, fjeremic commented
@genie-omr build all

2021-02-05 21:43 UTC, merged