Update AliasBuilder and SymbolReferenceTable following extensible class convention
eclipse/omr pull request #5766
Opened 2021-01-23 01:55 UTC by jamesgua

- AliasBuilder
  - SymbolReferenceTable

Add OMR_EXTENSIBLE macro and using self() within member functions

Signed-off-by: James Guan <jamesgua@ca.ibm.com>

2021-01-28 18:59 UTC, 0xdaryl requested changes
Merging this as-is will undoubtedly cause downstream projects to break if they are running linters checking for correct usage of extensible classes.  I would like to give them an opportunity to catch up with these changes.

Could you re-submit these changes just as you have them but without adding the `OMR_EXTENSIBLE` attribute to the class?  This way, known downstream projects can make the changes they need and once those are completed you can decorate the class with the `OMR_EXTENSIBLE` attribute.

2021-01-28 18:59 UTC, 0xdaryl commented on compiler/compile/OMRSymbolReferenceTable_inlines.hpp
> +#endif
Fix EOF marker.

2021-01-28 18:59 UTC, 0xdaryl commented on compiler/compile/OMRSymbolReferenceTable_inlines.hpp
> + * Copyright (c) 2021 IBM Corp. and others
Fix copyright style (2 dates)

2021-01-28 18:59 UTC, 0xdaryl commented on compiler/compile/OMRSymbolReferenceTable_inlines.hpp
> +#ifndef OMR_SYMBOLREFERENCETABLE_INLINE_INCL
Use `INLINES` instead of `INLINE` for consistency elsewhere.

2021-01-28 18:59 UTC, 0xdaryl commented on compiler/compile/SymbolReferenceTable_inlines.hpp
> + * Copyright (c) 2021 IBM Corp. and others
Fix copyright date (2 dates)

2021-01-28 20:05 UTC, 0xdaryl commented
Actually, you have to leave the `self()` call where it is as well for now as downstream projects won't know to find it in the `SymbolReferenceTable_inlines.hpp` file.

2021-01-28 20:05 UTC, genie-omr commented
Can one of the admins verify this patch?

2021-01-28 20:05 UTC, genie-omr commented
Can one of the admins verify this patch?

2021-02-02 00:19 UTC, jamesgua commented on compiler/compile/SymbolReferenceTable_inlines.hpp
> + * Copyright (c) 2021 IBM Corp. and others
updated per your suggestion, pls take another look. Thx!

2022-04-19 22:45 UTC, closed without merging