Remove unused applyUserOptions on Power
eclipse/omr pull request #5767
Opened 2021-01-25 20:33 UTC by AlenBadel

Removing the unused implementation of applyUserOptions.
applyUserOptions was implemented only on Power so that on startup it was possible to disable P10 support when TR_EnableExperimentalPower10Support is not set.
applyUserOptions was ultimately implemented but never used.
Since the method is not implemented on any other platform, it should be removed from the class.

Signed-off-by: AlenBadel <Alen.Badel@ibm.com>

2021-01-25 20:33 UTC, genie-omr commented
Can one of the admins verify this patch?

2021-01-25 20:33 UTC, genie-omr commented
Can one of the admins verify this patch?

2021-01-25 20:33 UTC, genie-omr commented
Can one of the admins verify this patch?

2021-01-29 00:41 UTC, 0xdaryl requested changes
Please update the copyright headers for 2021 as appropriate.

2021-02-03 22:46 UTC, gita-omr commented
@zl-wang fyi

2021-02-04 14:48 UTC, gita-omr approved these changes
Indeed does not seem to be used anywhere.

2021-02-04 14:55 UTC, 0xdaryl commented
@genie-omr build all

2021-02-04 16:29 UTC, 0xdaryl approved these changes

2021-02-04 16:29 UTC, 0xdaryl commented
I am ignoring the RISC-V CI failure.  Merging.

2021-02-04 16:29 UTC, merged