CMake: Fix handling of ddr scanner
eclipse/omr pull request #5771
Opened 2021-01-27 15:24 UTC by dnakamura

- Enable support for z/OS
- Don't compile DwarfFunctions on linux (matches behaviour of makefiles)

Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

2021-01-27 15:24 UTC, dnakamura commented
@genie-omr build all

2021-01-28 18:46 UTC, 0xdaryl commented
@keithc-ca : would you mind reviewing this please ?

2021-01-28 19:09 UTC, keithc-ca requested changes

2021-01-28 19:09 UTC, keithc-ca commented on ddr/lib/ddr-scanner/CMakeLists.txt
> +	set(HAVE_LIBDWARF_LIBDWARF_H ON CACHE BOOL "")
I think a better place for this is in `FindLibDwarf.cmake`.

2021-04-23 14:22 UTC, keithc-ca commented on cmake/modules/FindLibDwarf.cmake
> +	# On zos we don't want libz
The platform is called 'z/OS', and please finish sentences with a period.

2021-05-07 14:35 UTC, dnakamura commented
Jenkins build all

2021-05-07 21:14 UTC, keithc-ca approved these changes

2021-05-11 13:41 UTC, dnakamura commented
@0xdaryl  this should be good to merge

2021-05-25 14:14 UTC, dnakamura commented
@fjeremic  can you take a look at this?

2021-05-25 15:09 UTC, fjeremic commented
@dnakamura GitHub is telling me there are conflicts on this branch, but it doesn't say what they are. Weird. It won't let me merge.

2021-05-25 16:13 UTC, keithc-ca commented
Very weird. https://github.com/CAS-Atlantic/omr says it's even with this repo, which shows this was merged:
```
Author: Filip Jeremic <fjeremic@ca.ibm.com> 2021-05-25 11:07:41
Committer: GitHub <noreply@github.com> 2021-05-25 11:07:41
```
I fetched from this repo and also have that merge commit: 5750821e93a466eccc7084d7a7cfffc01461dbcb.

2021-05-25 16:18 UTC, dnakamura commented
Closing as it appears it got merged

2021-05-25 16:18 UTC, closed without merging