WIP: Remove x87 floating point support
eclipse/omr pull request #5973
Opened 2021-04-29 18:48 UTC by BradleyWood

Refactoring FPTreeEvaluator in process of removing x87 support. Removed conditional logic to always use SSE.

Refactor float/double to long conversion on x86 to use SSE instead of x87 instructions.

Issue: #946

2021-04-30 02:03 UTC, fjeremic commented
Looks like you have duplicate commits here and a missing line break in the first one.

2021-04-30 02:08 UTC, BradleyWood commented
I will squash those two before I finish with this.

2021-05-04 12:50 UTC, 0xdaryl reviewed
In general the code changes here look good. As expected, there is some trickiness on the f/d -> i/l paths, as well as floating point remainder that we need to sort out.

The existing conversion operations adhere to Java semantics, in particular on the overflow, infinity, and NaN cases.  OMR itself doesn't define default floating point semantics (it probably should, but that is something to come later).  Because of some of the complications introduced to ensure the converted value follows Java semantics (e.g., the use of snippets and runtime assembler helpers) I think it makes sense to relocate the `f2i`/`f2l`/`d2i`/`d2l` evaluators to OpenJ9 (and taking the snippets with them if that is their only use).  In its place, OMR could implement a much simpler implementation more akin to C conversion semantics (using round-to-zero, i.e., truncation) where handling of the special values is not done.

On 64-bit, this means using the SSE conversion instructions without checking for the indefinite result (because handling the special result would mean we are going to impose floating point semantics that we don't have defined in OMR.  On 32-bit, this means that `FISTP m32/m64` instructions can be used if the FPCW is set to truncation, or on processors that support SSE3 use the `FISTTP m32/m64` instructions which do truncation without having to set the control word.  You will have to add support for `FISTTP` and check when we are allowed to use it.  This can be used in OMR without requiring support for x87 register assignment by producing pre-encoded instructions.  That is,
```
   mov [m32], xmm6
   fld m32                ; Loads m32 to ST0 always; encoding doesn't require x87 RA
   fisttp intm32          ; Converts, truncates, pops x87 stack, and stores in intm32.
                          ; Encoding doesn't require x87 RA.
```
If you use `FISTP` on older processors without SSE3 support you will have to preserve the `FPCW`, set the `FPCW` to truncating rounding mode, do the `FISTP`, and then reset the `FPCW` back to what it was before.

Floating point remainder is trickier.  At the moment, the FP modulus implementation on 64-bit won't actually work because it requires a helper to do the computation.  However, the helper implementation doesn't exist in OMR so non-Java runtimes will simply crash.  I think the floating point remainder evaluators should be relocated to OpenJ9.  In OMR, I think we should leave these opcodes as unimplemented on x86.  Like the conversion opcodes, the semantics of floating point modulus in OMR is unspecified, so providing an implementation in OMR is arbitrary anyway.

2021-06-21 18:05 UTC, fjeremic commented
@BradleyWood there are some conflicts here.

2021-06-21 22:06 UTC, BradleyWood commented
[Fixing Conflicts](https://github.com/eclipse/omr/compare/41e3cea913f87bfa6a69fcd392e821c67e90171e..770a073c7ba2356a730462062c23b3e214ad5d73)

2021-06-22 17:02 UTC, 0xdaryl commented
Jenkins build xlinux,win,osx

2021-06-29 12:47 UTC, 0xdaryl requested changes
I did a more thorough final review of this and have a few final comments.

2021-06-29 12:47 UTC, 0xdaryl commented on compiler/x/codegen/FPTreeEvaluator.cpp
> +   TR_ReturnInfo returnInfo = (returnRegister->isSinglePrecision()) ? TR_FloatXMMReturn : TR_DoubleXMMReturn;
Can you sink this down to where it is actually used?  It makes the code more readable.

2021-06-29 12:47 UTC, 0xdaryl commented on compiler/x/codegen/FPTreeEvaluator.cpp
> +      targetRegister = TR::TreeEvaluator::performHelperCall(node, helperSymRef, nodeIsDouble ? TR::dcall : TR::fcall, false, cg);
To save code footprint can you rewrite this as:
```
TR_RuntimeHelper remainderHelper;
if (cg->comp()->target().is64Bit())
   {
   remainderHelper = nodeIsDouble ? TR_AMD64doubleRemainder : TR_AMD64floatRemainder;
   }
else
   {
   remainderHelper = nodeIsDouble ? TR_IA32doubleRemainderSSE : TR_IA32floatRemainderSSE;
   }

TR::SymbolReference *helperSymRef = cg->symRefTab()->findOrCreateRuntimeHelper(remainderHelper);
targetRegister = TR::TreeEvaluator::performHelperCall(node, helperSymRef, nodeIsDouble ? TR::dcall : TR::fcall, false, cg);

```

2021-06-29 12:47 UTC, 0xdaryl commented on compiler/x/codegen/FPTreeEvaluator.cpp
> +      generateLabelInstruction(TR::InstOpCode::JE4, node, exceptionLabel, cg);
Put this JE4 (and the one in the if branch) after the if/else paths to reduce code footprint.

2021-06-29 12:47 UTC, 0xdaryl commented on compiler/x/codegen/FPTreeEvaluator.cpp
> +      globalReg = TR::TreeEvaluator::coerceFPRToXMMR(child, globalReg, cg);
Delete these two lines.  The globalReg can't be anything other than a TR_FPR.  You could add a TR_FATAL_ASSERT for this instead.

2021-06-29 12:47 UTC, 0xdaryl commented on compiler/x/codegen/FPTreeEvaluator.cpp
> +      globalReg = TR::TreeEvaluator::coerceFPRToXMMR(child, globalReg, cg);
Delete these two lines. The globalReg can't be anything other than a TR_FPR. You could add a TR_FATAL_ASSERT for this instead.

2021-06-29 14:59 UTC, BradleyWood commented
See [force-push](https://github.com/eclipse/omr/compare/83e0c240b44271fbf5c2cf5b524f2a36a68160cc..3f3242b2fcc50a09c5163540ef40a0e7860290e3)

2021-06-30 01:29 UTC, 0xdaryl commented
Jenkins build xlinux,win,osx

2021-07-07 01:48 UTC, 0xdaryl approved these changes

2021-07-07 01:49 UTC, 0xdaryl commented
Can you rebase to resolve the merge conflicts please?

2021-07-07 02:15 UTC, BradleyWood commented
> Can you rebase to resolve the merge conflicts please?

There was a single conflict inside a function that was deletec. Should not affect the build.

2021-07-07 20:01 UTC, fjeremic commented
Jenkins build all

2021-07-13 16:49 UTC, merged