Fix omrthread_get_stack_range on Mac OSX
eclipse/omr pull request #5986
Opened 2021-05-07 19:49 UTC by tajila

Fix omrthread_get_stack_range on Mac OSX

On Mac OSX stack start means where sp begins not the low memory.
This is the opposite of how it is on linux and how this API is
intended to be used.

Signed-off-by: Tobi Ajila <atobia@ca.ibm.com>

2021-05-07 19:50 UTC, tajila commented
@pshipton Please review these changes

2021-05-10 13:37 UTC, tajila commented on thread/common/omrthreadinspect.c
> +	*stackStart = (void *)((uintptr_t)*stackEnd - stackSize);
We need to handle that case also, as the launcher will use Xss to set the stack size, I plan do that after these changes.

2021-05-10 13:58 UTC, tajila commented
@fjeremic please review these changes

2021-05-10 14:00 UTC, pshipton commented on thread/common/omrthreadinspect.c
> +	*stackStart = (void *)((uintptr_t)*stackEnd - stackSize);
FYI I did find one example that tested pthread_get_stackaddr_np against a stack variable to determine if it was before or after. Not sure if the behaviour could be different on different supported versions of the OS. We support 10.10 and later.

The javacore prints the native stack range, I get the following on osx1011-x86-1, which indicates omrthread_get_stack_range() is working as-is.
`3XMTHREADINFO2            (native stack address range from:0x00007000002E0000, to:0x00007000003E0000, size:0x100000)`

And on  osx1014-x86-1
`3XMTHREADINFO2            (native stack address range from:0x000070000ECB0000, to:0x000070000EDB0000, size:0x100000)`

2021-05-10 14:01 UTC, pshipton commented
I approved and I can't remove that, but pls hold off merging until https://github.com/eclipse/omr/pull/5986#discussion_r629384662 is addressed.

2021-05-10 14:27 UTC, fjeremic requested changes
See review from Peter. Marking changes requested so I don't accidentally merge.

2021-05-10 15:46 UTC, tajila commented on thread/common/omrthreadinspect.c
> +	*stackStart = (void *)((uintptr_t)*stackEnd - stackSize);
I tried the changes on Mac OSX 10.13

The stack range on the main java thread was: 
```
3XMTHREADINFO      "main" J9VMThread:0x00000000135A2A00, omrthread_t:0x00007F7EFD003450, java/lang/Thread:0x00000000FFF055B8, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1, isDaemon:false)
3XMTHREADINFO1            (native thread ID:0xD777, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00001020)
3XMTHREADINFO2            (native stack address range from:0x0000700000C5D000, to:0x0000700000CDD000, size:0x80000)
```

I verified this with printing out a trace point with the address of the ELS:

```
15:38:29.537*0x135a2a00            j9vm.680      - OS Stack free=517864, current native sp=0000700000CDAC90
15:38:29.537 0x135a2a00            j9vm.680      - OS Stack free=516040, current native sp=0000700000CDA570
15:38:29.537 0x135a2a00            j9vm.680      - OS Stack free=514216, current native sp=0000700000CD9E50
15:38:29.538 0x135a2a00            j9vm.680      - OS Stack free=516040, current native sp=0000700000CDA570
15:38:29.538 0x135a2a00            j9vm.680      - OS Stack free=514264, current native sp=0000700000CD9E80
15:38:29.538 0x135a2a00            j9vm.680      - OS Stack free=514216, current native sp=0000700000CD9E50
15:38:29.538 0x135a2a00            j9vm.680      - OS Stack free=512392, current native sp=0000700000CD9730
```

> The javacore prints the native stack range, I get the following on osx1011-x86-1, which indicates omrthread_get_stack_range() is working as-is.

The fact that the `stackStart` is lower memory than `stackEnd` doesn't necessarily mean that it is working correctly. 

The original code is setting `stackStart` to `pthread_get_stackaddr_np` then adding stackSize to `stackStart` to get `stackEnd`, so `stackStart` will always be lower memory than `stackEnd`.  One needs to check that the `sp` is actually within that range.

2021-05-10 15:50 UTC, tajila commented on thread/common/omrthreadinspect.c
> +	*stackStart = (void *)((uintptr_t)*stackEnd - stackSize);
I added printf statements to a build without these changes when the J9VMthreads are started:

```
11:45:54  vmthread=0x11256400 start=0x700003f1a000 end=0x700003f9a000 requested size=262144 currentSP=0x700003f18e38 
11:45:54  vmthread=0x1125a100 start=0x700004060000 end=0x700004160000 requested size=262144 currentSP=0x70000405dc68 
11:45:54  vmthread=0x1125dd00 start=0x700004163000 end=0x700004263000 requested size=262144 currentSP=0x700004160c68 
11:45:54  vmthread=0x11261a00 start=0x700004266000 end=0x700004366000 requested size=262144 currentSP=0x700004263c68 
11:45:54  vmthread=0x11265600 start=0x700004369000 end=0x700004469000 requested size=262144 currentSP=0x700004366c68 
11:45:54  vmthread=0x11269200 start=0x70000446c000 end=0x70000456c000 requested size=262144 currentSP=0x700004469c68 
11:45:54  vmthread=0x1126cf00 start=0x70000456f000 end=0x70000466f000 requested size=262144 currentSP=0x70000456cc68 
11:45:54  vmthread=0x11270b00 start=0x700004672000 end=0x700004772000 requested size=262144 currentSP=0x70000466fc68 
11:45:54  vmthread=0x11274700 start=0x700004775000 end=0x700004875000 requested size=262144 currentSP=0x700004772c68 
11:45:54  vmthread=0x11278400 start=0x7000047b8000 end=0x7000047f8000 requested size=262144 currentSP=0x7000047b5b08 
11:45:54  vmthread=0x1127c000 start=0x7000047db000 end=0x7000047fb000 requested size=262144 currentSP=0x7000047d8c78 
```

This demonstrates that the reported range is incorrect.

This was done on OSX 10.14

2021-05-10 16:55 UTC, pshipton commented on thread/common/omrthreadinspect.c
> +	*stackStart = (void *)((uintptr_t)*stackEnd - stackSize);
Pls double check on 10.11 (osxrt3) to make sure it's the same

2021-05-10 22:21 UTC, pshipton approved these changes

2021-05-10 22:21 UTC, pshipton commented
lgtm

2021-05-10 22:22 UTC, fjeremic commented
Jenkins build all

2021-05-10 23:35 UTC, merged