Implemented Changes in #5912
eclipse/omr pull request #5988
Opened 2021-05-09 16:02 UTC by rlkenny98

This patch implements the proposed changes in #5912.

This commit moved all instances of the _ialoadUnneeded attribute to the Z subfolder:
 - Moved  "List<TR_Pair<TR::Node, int32_t> > _ialoadUnneeded;" from compiler/codegen/OMRCodeGenerator.hpp to z/codegen/OMRCodeGenerator.hpp
- Moved "_ialoadUnneeded(comp->trMemory())," from compiler/codegen/OMRCodegenerator.cpp to z/codegen/OMRCodeGenerator.cpp

Closes: #5912

2021-05-10 14:30 UTC, fjeremic requested changes

2021-05-10 14:30 UTC, fjeremic commented on compiler/z/codegen/OMRCodeGenerator.hpp
> +   List<TR_Pair<TR::Node, int32_t> > _ialoadUnneeded;
This should be a private field as it is not currently used by any subclasses of `CodeGenerator`. Could we move it down under the `private:` section where all the other fields are?

2021-05-10 17:10 UTC, rlkenny98 commented
@fjeremic Okay, I'll move it to the private section and commit with the message changes you talked about!

2021-05-10 18:09 UTC, rlkenny98 commented
@fjeremic Okay I changed the commit message to be formatted according to the guidelines. Let me know if there is anything else I should fix!

2021-05-10 19:42 UTC, rlkenny98 commented
@fjeremic I'm fairly new to Git and have been researching the best way to do this. Should I just make a new commit containing everything discussed here and open a new PR?

2021-05-10 19:53 UTC, fjeremic commented
> @fjeremic I'm fairly new to Git and have been researching the best way to do this. Should I just make a new commit containing everything discussed here and open a new PR?

@rlkenny98 I took a look at your branch here:
https://github.com/rlkenny98/omr/commits/robert-kenny-compiler-codegen

The first upstream commit is cd2fd54f0bf5f04086c7481490b090ec68c03b4c. So to squash your commits here, do an interactive rebase against this commit, so in your case `git rebase -i cd2fd54`. This will bring up the interactive rebase in your configured git editor. Then just simply replace `pick` of the last three commits with `squash` and continue the rebase. It will at some point ask you to merge the commit messages. We want the resulting commit to have the same message as you have in 35c9293. After you're done force push your changes to your branch in your fork and this PR will be automatically updated.

Here is an example:
https://www.git-tower.com/learn/git/faq/git-squash/

See _How to Squash Your Commits_ section. PS you can (and probably should for learning purposes) do all of this on the commandline.

2021-05-12 16:19 UTC, rlkenny98 commented
Hey @fjeremic @0xdaryl finishing this up today! Got preoccupied with other responsibilities. Thank you for your help

2021-05-12 21:06 UTC, rlkenny98 commented
@fjeremic got everything into one commit! let me know if there is anything else to do on my end! thanks :)

2021-05-13 00:40 UTC, fjeremic commented
Jenkins build all

2021-05-13 12:47 UTC, fjeremic approved these changes

2021-05-13 12:47 UTC, fjeremic commented
Thanks for fixing this @rlkenny98! Much appreciated.

2021-05-13 12:47 UTC, merged