RISC-V: implement calls without trampolines
eclipse/omr pull request #5989
Opened 2021-05-10 10:52 UTC by janvrany

This PR adds support for calls without trampolines as a temporary solution until #2017 is implemented.

2021-05-10 11:05 UTC, janvrany commented
As of now, there's a bug somewhere in linkage making a number  `LinkageTest`s failing - I decided to keep this PR as draft until I hunt down that bug and fix it so tests pass. 

Commit 28f7225 is the one that add support for calls, the rest is just a bunch of fixes and cleanups. These should probably go into separate PR as they have nothing to do with calls, but I'll split this PR once I have tests passing (to avoid "oops, fix this" commits). I'd appreciate pre-review of commits before 28f7225, especially commit 31b8e5a (I'm not 100% sure of it but clearly it prevents `TR_ASSERT()`ion failure when running `LinkageTests`.

Finally, @knn-k, maybe it'd make sense to do d33e1ad also for AArch64?

2021-05-10 11:09 UTC, janvrany commented
jenkins build all

2021-05-10 11:58 UTC, knn-k commented
It is not only AArch64 but p/z/arm platforms also use the name `_numberOfDependencyGPRegisters`.  An example:
https://github.com/eclipse/omr/blob/cd2fd54f0bf5f04086c7481490b090ec68c03b4c/compiler/p/codegen/OMRLinkage.hpp#L121

I agree that the name is confusing.

2021-05-22 20:20 UTC, janvrany commented
Commit df0db05 fixes passing of integer parameters on stack. 

However, passing float arguments is still broken. The problem is that on RISC-V, if FP there's no more FP argument register available (that is, for 9th and more FP argument), it is passed in integer argument register (if available). An excerpt from
[RISC-V PSABI spec](https://github.com/riscv/riscv-elf-psabi-doc/blob/master/riscv-elf.md#hardware-floating-point-calling-convention):

> A real floating-point argument is passed in a floating-point argument register if it is no more than FLEN bits wide and at least one floating-point argument register is available. Otherwise, it is passed according to the integer calling convention. When a floating-point argument narrower than FLEN bits is passed in a floating-point register, it is 1-extended (NaN-boxed) to FLEN bits.

Funny enough, jit-to-native FP tests pass even for 9 arguments because jitted code does not clobber `a0` (first integer argument register). 

I'll update this PR once correct behavior is implemented.

2021-06-12 09:31 UTC, janvrany commented
jenkins build riscv

2021-06-12 11:17 UTC, janvrany commented
I have fixed all remaining issues so now both `CallTest` and `LinkageTest`. Therefore I think this PR is ready for review.

2021-06-14 11:59 UTC, 0xdaryl requested changes

2021-06-14 11:59 UTC, 0xdaryl commented on compiler/riscv/codegen/OMRLinkage.hpp
> +   virtual TR::MemoryReference *getOutgoingArgumentMemRef(TR::Register *argMemReg, int offset, TR::Register *argReg, TR::InstOpCode::Mnemonic opCode, TR::RVMemoryArgument &memArg);
The convention in the compiler is to use an explicit-sized integer type:  `int32_t`

2021-06-14 11:59 UTC, 0xdaryl commented on compiler/riscv/codegen/OMRMachine.cpp
> +   TR_ASSERT(sourceReg->getKind() == targetReg->getKind(), "Source and target register kind mismatch.");
These should be `TR_ASSERT_FATAL` to be of any use.

2021-06-14 11:59 UTC, 0xdaryl commented on compiler/riscv/codegen/OMRMachine.cpp
> +         TR_ASSERT(sourceReg->isSinglePrecision() == targetReg->isSinglePrecision(), "Source and target register size mismatch");
`TR_ASSERT_FATAL`

2021-06-14 11:59 UTC, 0xdaryl commented on compiler/riscv/codegen/RVInstruction.cpp
> +         offset = (uint8_t*)getSymbolReference()->getMethodAddress() - cursor;
Please make this a `reinterpret_cast` as the compiler is starting to adopt the C++ casts exclusively.

2021-06-14 11:59 UTC, 0xdaryl commented on compiler/riscv/codegen/RVInstruction.cpp
> +      uint8_t* destination = (uint8_t*)(getLabelSymbol()->getCodeLocation());
Please make this a `reinterpret_cast` as the compiler is starting to adopt the C++ casts exclusively.

2021-06-14 11:59 UTC, 0xdaryl commented on compiler/riscv/codegen/RVSystemLinkage.cpp
> +   for (int i = numIntegerArgs + numFloatArgsPassedInGPRs; i < properties.getNumIntArgRegs(); i++)
Compiler convention is to use explicitly-sized integers: `int32_t`

2021-06-14 11:59 UTC, 0xdaryl commented on fvtest/compilertriltest/CallTest.cpp
> +	SKIP_ON_PPC(MissingImplementation) << "Test is skipped on POWER because calls are not currently supported (see issue #1645)";
Fix indenting.

2021-06-14 11:59 UTC, 0xdaryl commented on compiler/riscv/codegen/RVSystemLinkage.cpp
> +         loadConstant64(cg(), callNode, (int64_t)targetAddr, ra);
Please make this a `static_cast` as the compiler is starting to adopt the C++ casts exclusively.

2021-06-16 13:41 UTC, janvrany commented
jenkins build riscv

2021-06-16 15:03 UTC, 0xdaryl approved these changes

2021-06-16 15:06 UTC, merged