Allow 64K page size as a valid option on AIX
eclipse/omr pull request #5995
Opened 2021-05-11 20:56 UTC by singh264

xlpCodeCacheTests fails on AIX because the default
code cache large page size 64K is absent in the
list of available code cache large page sizes
output by `-verbose:sizes`.

Include 64K in the list of available code cache
large page sizes for the test to parse as the
expected page size when no `-Xlp` option is
supplied and the default page size is used.

Signed-off-by: Amarpreet Singh amarpreet1997@gmail.com

2021-05-12 17:54 UTC, singh264 commented
@ymanton requesting feedback

2021-05-13 18:26 UTC, ymanton requested changes
LGTM, just update the comment.

2021-05-13 19:20 UTC, singh264 commented on port/aix/omrvmem.c
>  		 */
Updated comment to include 64K as supported page size.

2021-05-13 21:50 UTC, ymanton approved these changes

2021-05-14 00:01 UTC, 0xdaryl commented
Could you update the commit title to reflect what the change does and not which test it fixes please?  It is more useful in the git history that way.

@babsingh please review.

2021-05-14 00:01 UTC, 0xdaryl requested changes
Formally requesting a change per my comment above.

2021-05-14 11:59 UTC, babsingh requested changes
code logic looks good to me. only formatting changes have been suggested.

commit title suggestion: `Allow 64K page size as a valid option on AIX`

2021-05-14 11:59 UTC, babsingh commented on port/aix/omrvmem.c
>  			(SIXTEEN_M == validPageSize))
edited code should be reformatted as per coding standards: https://github.com/eclipse/omr/blob/master/doc/CodingStandard.md#formatting-conditions
```suggestion
		if ((OMRPORT_VMEM_MEMORY_MODE_EXECUTE != (OMRPORT_VMEM_MEMORY_MODE_EXECUTE & mode))
			|| (SIXTY_FOUR_K == validPageSize)
			|| (SIXTEEN_M == validPageSize)
```

2021-05-14 11:59 UTC, babsingh commented on port/aix/omrvmem.c
>  		if ((OMRPORT_VMEM_MEMORY_MODE_EXECUTE != (OMRPORT_VMEM_MEMORY_MODE_EXECUTE & mode)) ||
https://github.com/eclipse/omr/blob/master/doc/CodingStandard.md#formatting-conditions
```suggestion
		if ((OMRPORT_VMEM_MEMORY_MODE_EXECUTE != (OMRPORT_VMEM_MEMORY_MODE_EXECUTE & mode))
```

2021-05-14 11:59 UTC, babsingh commented on port/aix/omrvmem.c
>  		{
https://github.com/eclipse/omr/blob/master/doc/CodingStandard.md#formatting-conditions
```suggestion
			|| ((TRUE == codeCacheConsolidationEnabled) && (SIXTEEN_M == validPageSize))
			|| (SIXTY_FOUR_K == validPageSize)
#endif /* defined(OMR_ENV_DATA64) */
		) {
```

2021-05-14 13:32 UTC, singh264 commented
@0xdaryl updated title from ~~`Fix xlpCodeCacheTests on AIX`~~ to `Allow 64K page size as a valid option on AIX`

@babsingh reformatted code as per [coding standards](https://github.com/eclipse/omr/blob/master/doc/CodingStandard.md#formatting-conditions)

2021-05-14 13:34 UTC, babsingh commented
The four commits need to be squashed into one commit.

2021-05-14 13:45 UTC, singh264 commented
> The four commits need to be squashed into one commit.

Squashed PR commits into one commit.

2021-05-14 14:00 UTC, babsingh approved these changes

2021-05-14 14:02 UTC, babsingh commented
Jenkins build all

2021-05-14 14:07 UTC, 0xdaryl approved these changes

2021-05-14 14:10 UTC, babsingh commented
@singh264 do we need to add test coverage for the failure?
https://github.com/eclipse/omr/blob/c58ed85788a6059407a42814ba7845aaa0a8f8cf/fvtest/porttest/omrvmemTest.cpp#L3032

2021-05-17 13:11 UTC, singh264 commented
@babsingh I don't think we need to add test coverage in `omrvmemTest.cpp` because

(1) [xlpCodeCacheTests](https://github.com/eclipse-openj9/openj9/blob/e495256d209c71f42c8472b267407fe5061c86bd/test/functional/VM_Test/src/j9vm/test/xlpcodecache/XlpCodeCacheOptionsTestRunner.java#L97) covers the PR changes, and 

(2) `omrvmem_testFindValidPageSize_impl(..)` (on line 3032) seems to be excluded from AIX PPC because its usage exists inside `#if (defined(LINUX) && !defined(LINUXPPC)) || defined(OMR_OS_WINDOWS) || defined(OSX)` block (on line 2861) and is absent inside `#elif defined(AIXPPC) || defined(LINUXPPC)` block (on line 3029).

2021-05-17 14:29 UTC, babsingh commented
@0xdaryl The test suggested in https://github.com/eclipse/omr/pull/5995#issuecomment-841268718 is not run on AIX. Relying upon `xlpCodeCacheTests` for test coverage is sufficient. So, this PR is good to merge.

2021-05-17 14:29 UTC, babsingh approved these changes

2021-05-17 14:40 UTC, merged