Fix Linux compiler warnings when DUMP_DBG is defined
eclipse/omr pull request #6390
Opened 2022-03-07 11:09 UTC by davidjmccann

If DUMP_DBG is defined on Linux (which it usually isn't since it's for debugging purposes), then four warnings are emitted:

./linux/omrosdump_helpers.c:783:6: error: variable 'bytesread' set but not used [-Werror,-Wunused-but-set-variable]
        int bytesread = 0;
            ^
./linux/omrosdump_helpers.c:782:6: error: variable 'offset' set but not used [-Werror,-Wunused-but-set-variable]
        int offset = 0;
            ^
./linux/omrosdump_helpers.c:827:6: error: variable 'inode' set but not used [-Werror,-Wunused-but-set-variable]
        int inode;
            ^
./linux/omrosdump_helpers.c:825:6: error: variable 'offset' set but not used [-Werror,-Wunused-but-set-variable]
        int offset;

The use of J9_IGNORE_RETURNVAL prevents these warnings.

Signed-off-by: David McCann <mccannd@uk.ibm.com>

2022-03-07 16:30 UTC, davidjmccann commented
Sorry, extra commit added in error....

2022-03-07 21:01 UTC, babsingh commented
Jenkins build all

2022-03-07 22:21 UTC, babsingh commented
Jenkins build win

2022-03-08 00:17 UTC, babsingh approved these changes

2022-03-09 18:35 UTC, davidjmccann commented
Sorry, but I found an additional warning re: "device" on a different compiler (I'd been using clang, but this additional one was on gcc). Could you check you're happy with the changes?

2022-03-10 04:22 UTC, babsingh requested changes
I see that you have updated the commit message with
```
./linux/omrosdump_helpers.c: In function 'printMemoryMap':
./linux/omrosdump_helpers.c:823:14: error: variable 'device' set but not used [-Werror=unused-but-set-variable]
  823 |         char device[6];
```

The pull requests description should also include this detail.

2022-03-10 04:22 UTC, babsingh commented on port/linux/omrosdump_helpers.c
>  					next++;
```suggestion
					/* skip over the device (+5) and get the inode (+1) */
					next += 6;
```

2022-03-10 06:46 UTC, davidjmccann commented
> The pull request's description should also include this detail.

Done

2022-03-10 15:06 UTC, babsingh commented on port/linux/omrosdump_helpers.c
>  					next++;
This was missed?

2022-03-10 15:52 UTC, davidjmccann commented on port/linux/omrosdump_helpers.c
>  					next++;
Yes, sorry, missed that. Try now.

2022-03-10 16:26 UTC, babsingh commented
jenkins build all

2022-03-10 18:11 UTC, babsingh approved these changes
LGTM. ++ @0xdaryl.

2022-03-11 01:35 UTC, 0xdaryl approved these changes

2022-03-11 01:35 UTC, merged