Move J9 specific i386 evaluators to OpenJ9
eclipse/omr pull request #6482
Opened 2022-04-19 14:03 UTC by BradleyWood

Signed-off-by: BradleyWood <bradley.wood@ibm.com>

Closes #6343

2022-04-19 14:12 UTC, BradleyWood commented
@dsouzai Would you mind reviewing?

This should have downstream dependency eclipse-openj9/openj9#14925 because of the change at:

https://github.com/BradleyWood/omr/blob/668ee521c2d9a5ee0e6f7e756b9b004bb2779459/compiler/x/i386/codegen/OMRTreeEvaluator.cpp#L5015

2022-04-19 18:42 UTC, dsouzai requested changes

2022-04-19 18:42 UTC, dsouzai commented on compiler/x/i386/codegen/OMRTreeEvaluator.cpp
> -#endif
See https://github.com/eclipse-openj9/openj9/pull/14925#discussion_r853374839

2022-04-19 18:42 UTC, dsouzai commented on compiler/x/i386/codegen/OMRTreeEvaluator.cpp
> -
See https://github.com/eclipse-openj9/openj9/pull/14925#discussion_r853377242

2022-04-20 15:12 UTC, BradleyWood commented on compiler/x/i386/codegen/OMRTreeEvaluator.cpp
> -#endif
See [force-push](https://github.com/eclipse/omr/compare/668ee521c2d9a5ee0e6f7e756b9b004bb2779459..c6c201c3f909051a1462a5cb20a2060512d94ce1)

2022-04-21 15:25 UTC, dsouzai approved these changes

2022-04-21 15:25 UTC, dsouzai commented
jenkins build all

2022-04-21 15:50 UTC, dsouzai commented
jenkins build x32linux,win

2022-04-22 14:14 UTC, dsouzai commented
Because this is a coordinated merge, gonna do it on Monday so there's no surprises over the weekend.

2022-04-25 14:09 UTC, merged