Fix omrfileTest failures when running as root
eclipse/omr pull request #6510
Opened 2022-05-11 14:55 UTC by EricYangIBM

PortFileTest2.file_test27 and PortFileTest2.file_test29 fail when runnning
as root. Add logic to change test behaviour if tests are being run as root.

Signed-off-by: Eric Yang <eric.yang@ibm.com>

2022-05-11 14:58 UTC, EricYangIBM commented
The only changes are the checks for euid and the change from `rc` -> `fd2` in the error messages for (erroneously) successfully opening read only file for writing and vice versa, which is an error as the error message specifically has `fd` in it.

For reference, the failures:
```
6: /root/docker_hostdir/temp/omr/fvtest/porttest/omrfileTest.cpp line 3498: omrfile_test27 opened read-only file for writing fd=0 expected -1
6: 
6:              LastErrorNumber: -108
6:              LastErrorMessage: No such file or directory
6: 
6: /root/docker_hostdir/temp/omr/fvtest/porttest/testHelpers.cpp:109: Failure
6: Value of: 0 == numberFailedTestsInComponent
6:   Actual: false
6: Expected: true
6: Test failed!
6: [  FAILED  ] PortFileTest2.file_test27 (0 ms)
6: /root/docker_hostdir/temp/omr/fvtest/porttest/omrfileTest.cpp line 3626: omrfile_test29 omrfile_chown() to root succeeded, should have failed
6: 
6:              LastErrorNumber: -108
6:              LastErrorMessage: No such file or directory
6: 
6: /root/docker_hostdir/temp/omr/fvtest/porttest/testHelpers.cpp:109: Failure
6: Value of: 0 == numberFailedTestsInComponent
6:   Actual: false
6: Expected: true
6: Test failed!
6: [  FAILED  ] PortFileTest2.file_test29 (0 ms)
```

2022-05-12 12:43 UTC, babsingh requested changes

2022-05-12 15:02 UTC, babsingh requested changes

2022-05-12 15:02 UTC, babsingh commented on fvtest/porttest/omrfileTest.cpp
> +#endif /* !defined(OMR_OS_WINDOWS) */
the `ifdef` at the closing brace can be avoided.
```suggestion
#if !defined(OMR_OS_WINDOWS)
	/* Do not run following test as a root user (euid == 0) as root can bypass file permissions. */
	if (0 != omrsysinfo_get_euid())
#endif /* !defined(OMR_OS_WINDOWS) */
	{
```

2022-05-12 17:37 UTC, babsingh commented
jenkins build all

2022-05-12 18:23 UTC, babsingh commented
jenkins build win

2022-05-13 15:09 UTC, babsingh commented
Restarting the zOS job since it timed out in finding a node.

2022-05-13 15:10 UTC, babsingh approved these changes

2022-05-16 15:51 UTC, babsingh commented
jenkins build zos

2022-05-16 16:47 UTC, jdmpapin commented
Jenkins build zos

2022-05-16 18:10 UTC, jdmpapin approved these changes

2022-05-16 18:10 UTC, merged