Add dump_test_create_dump_with_no_path
eclipse/omr pull request #6532
Opened 2022-05-27 13:31 UTC by davidjmccann

omrdump_create has different behaviour depending on whether the core file name contains a path separator, however there is currently no test for the code path where no path separator is found.

This commit introduces such a test.

Signed-off-by: David McCann mccannd@uk.ibm.com

2022-05-27 13:31 UTC, davidjmccann commented
jenkins build all

2022-05-27 13:59 UTC, babsingh commented
jenkins build all

2022-05-31 14:06 UTC, babsingh commented
> linux_riscv64_cross failure: https://ci.eclipse.org/omr/job/PullRequest-linux_riscv64_cross/685/

The below failure is not related to this PR.
```
12:00:38        Start 21: threadRealtimeTest
12:00:38  
12:00:38  21: Test command: /home/jenkins/qemu/build/qemu-riscv64 "-L" "/home/jenkins/riscv-debian/rootfs" "/home/jenkins/workspace/Build/build/fvtest/threadtest/omrthreadtest" "--gtest_output=xml:/home/jenkins/workspace/Build/build/fvtest/threadtest/omrthreadtest-results.xml" "--gtest_filter=ThreadCreateTest.*" "-realtime"
12:00:38  21: Test timeout computed to be: 10000000
12:00:38  Terminated
12:00:39  script returned exit code 143
```

2022-05-31 14:08 UTC, babsingh commented
**Port-library tests are disabled** on the below three platforms:
https://github.com/eclipse/omr/blob/e8fbaa89d507c042d619b78985fb72b187cbb61c/fvtest/porttest/CMakeLists.txt#L165-L168

**RESULTS for `dump_test_create_dump_with_no_path`** after enabling port-library tests on the above platforms:
- `linux_riscv64_cross`: **PASSES**. LOG: https://ci.eclipse.org/omr/job/PullRequest-linux_riscv64_cross/688/consoleText.
- `aix_ppc-64`: **PASSES**. LOG: https://ci.eclipse.org/omr/job/PullRequest-aix_ppc-64/3381/consoleText.
- `zos_390-64`: **FAILS**. LOG: https://ci.eclipse.org/omr/job/PullRequest-zos_390-64/3622/consoleText.

### zOS Failing Output
```
[2022-05-30T17:38:02.180Z] 14: Starting test dump_test_create_dump_with_no_path
[2022-05-30T17:38:02.180Z] 14: calling omrdump_create with filename: dump_test_create_dump_with_no_path
[2022-05-30T17:38:02.180Z] 14: JVM&|êè022I 
[2022-05-30T17:38:02.180Z] 14: IEATDUMP in progress with options SDATA=(LPA,GRSQ,LSQA,NUC,PSA,RGN,SQA,SUM,SWA,TRT)
[2022-05-30T17:38:02.180Z] 14: IEATDUMP failure for DSN='dump(test(create(dump(with(no(path.X&DS' RC=0x00000008 RSN=0x00000021
[2022-05-30T17:38:02.180Z] 14: /u/user1/workspace/Build/fvtest/porttest/omrdumpTest.cpp line  214: dump_test_create_dump_with_no_path omrdump_create returned: 8, with filename: dump(test(create(dump(with(no(path.X&DS
[2022-05-30T17:38:02.180Z] 14: 
[2022-05-30T17:38:02.180Z] 14:      LastErrorNumber: -101
[2022-05-30T17:38:02.180Z] 14:      LastErrorMessage: EDC5000I No error occurred.
[2022-05-30T17:38:02.180Z] 14: 
[2022-05-30T17:38:02.180Z] 14: Ending test dump_test_create_dump_with_no_path
[2022-05-30T17:38:02.180Z] 14: /u/user1/workspace/Build/fvtest/porttest/testHelpers.cpp:109: Failure
[2022-05-30T17:38:02.180Z] 14: Value of: 0 == numberFailedTestsInComponent
[2022-05-30T17:38:02.180Z] 14:   Actual: false
[2022-05-30T17:38:02.180Z] 14: Expected: true
[2022-05-30T17:38:02.180Z] 14: Test failed!
[2022-05-30T17:38:02.180Z] 14: [  FAILED  ] PortDumpTest.dump_test_create_dump_with_no_path (3 ms)
```

2022-05-31 14:15 UTC, babsingh commented
For the commit message, `the body should be wrapped at 72 characters, where reasonable`.

Ref: https://github.com/eclipse/omr/blob/2ad1ab75db7af817ca6935767313deaa548ca40e/CONTRIBUTING.md#commit-guidelines

Reformatted the line with 193 characters:
```
Add dump_test_create_dump_with_no_path

omrdump_create has different behaviour depending on whether the core
file name contains a path separator, however there is currently no
test for the code path where no path separator is found.

This commit introduces such a test.

Signed-off-by: David McCann mccannd@uk.ibm.com
```

2022-05-31 14:23 UTC, babsingh requested changes
New code is derived from old code, which does not follow the coding standard. But, new code needs to be re-worked to follow the coding standard.

Ref: https://github.com/eclipse/omr/blob/master/doc/CodingStandard.md#new-code.

2022-05-31 14:23 UTC, babsingh commented on fvtest/porttest/omrdumpTest.cpp
> +#else
Ref: https://github.com/eclipse/omr/blob/master/doc/CodingStandard.md#comment-conditional-compilation-directives-if-ifdef-ifndef-else-elif-endif

```suggestion
#else /* !defined(J9ZOS390) */
```

2022-05-31 14:23 UTC, babsingh commented on fvtest/porttest/omrdumpTest.cpp
> +#endif
```suggestion
#endif /* !defined(J9ZOS390) */
```

2022-05-31 14:23 UTC, babsingh commented on fvtest/porttest/omrdumpTest.cpp
> +		if (verifyFileRC == 0) {
```suggestion
		if (0 == verifyFileRC) {
```

2022-05-31 14:23 UTC, babsingh commented on fvtest/porttest/omrdumpTest.cpp
> +	if (rc == 0) {
Ref: https://github.com/eclipse/omr/blob/master/doc/CodingStandard.md#formatting-conditions
```suggestion
	if (0 == rc) {
```

2022-06-06 07:03 UTC, davidjmccann commented
@babsingh I've tried to make the requested updates. I suspect that the test is failing on z/OS because of the use of underscores, but I'm not sure. The reason that dump_test_create_dump_with_name seems to pass is because the full path is too long and so an automatic name is generated. Could you please re-run the test on z/OS?

2022-06-06 13:53 UTC, babsingh commented
jenkins build zos

2022-06-06 14:50 UTC, babsingh commented
In the previous zOS build, the test didn't run. Opened https://github.com/eclipse/omr/pull/6552 to re-enable this test.

2022-06-06 17:34 UTC, babsingh commented
jenkins build zos

2022-06-06 22:22 UTC, babsingh commented
> https://ci.eclipse.org/omr/job/PullRequest-zos_390-64/3643/

Retrying ... zOS build failed because of a network issue:

```
13:34:54  	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to ZISVJD10
13:34:54  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
13:34:54  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
13:34:54  		at hudson.remoting.Channel.call(Channel.java:1000)
```

2022-06-06 22:22 UTC, babsingh commented
jenkins build zos

2022-06-09 09:16 UTC, davidjmccann commented
Thanks @babsingh for your helpful investigations. I've uppercased the name, hoping that the lowercase might be what was causing the name to be rejected. Could you kick off another build on z?

2022-06-09 12:09 UTC, babsingh commented
jenkins build aix,zos,plinux

2022-06-16 18:14 UTC, babsingh commented
> https://ci.eclipse.org/omr/job/PullRequest-zos_390-64/3650/consoleFull

Based upon the log, upper-casing the name correctly generated the core-file. But, a new segfault was seen in the test. It will be easier to enable diagnostics and debug the segfault once https://github.com/eclipse/omr/pull/6525 is merged. Other alternative is to triage the failure on a zOS machine, which may not be easy to access.

```
08:36:30  14: [----------] 5 tests from PortDumpTest
08:36:30  14: IEATDUMP in progress with options SDATA=(LPA,GRSQ,LSQA,NUC,PSA,RGN,SQA,SUM,SWA,TRT)
08:36:33  14: IEATDUMP success for DSN='USER1.JVM.USER17.D220609.T124014.X&DS'
08:36:33  14: delete JVM.USER17.D220609.T124014.X001
08:36:33  14: IDC0550I ENTRY (A) USER1.JVM.USER17.D220609.T124014.X001 DELETED
08:36:33  14: JVM&|êè022I 
08:36:33  14: IEATDUMP in progress with options SDATA=(LPA,GRSQ,LSQA,NUC,PSA,RGN,SQA,SUM,SWA,TRT)
08:36:36  14: IEATDUMP success for DSN='DUMP.TEST.CREATE.DUMP.WITH.NO.PATH.X&DS'
08:36:36  14: CEE3204S The system detected a protection exception (System Completion Code=0C4).
08:36:36  14:          From entry point writeStringToBuffer at compile unit offset +000000001B09CFFE at entry offset +000000000000004E at address 000000001B09CFFE.
08:36:52  14/28 Test #14: porttest ..........................***Exception: SegFault 20.58 sec
```

> https://ci.eclipse.org/omr/job/PullRequest-linux_ppc-64_le_gcc/3653/console

Compiler issue: https://github.com/eclipse/omr/issues/6556. Unrelated to this PR.

```
08:20:38  30: [0;32m[----------] [m16 tests from AbsVPValueTest
08:20:38  30/30 Test #30: compunittest ......................***Exception: SegFault  0.30 sec
08:20:38  
08:20:38  97% tests passed, 1 tests failed out of 30
```

2022-07-04 12:55 UTC, babsingh commented
jenkins build aix,zos,plinux

2022-07-05 14:09 UTC, babsingh commented
> https://ci.eclipse.org/omr/job/PullRequest-zos_390-64/3688/consoleFull

- `linux_ppc-64_le_gcc` error is unrelated: #6571.
- On `zos_390-64`, core dump failed with `RC=0x00000008 RSN=0x00000026`. Meaning: Unable to allocate transaction dump data set. Action: Look at allocation failure messages. Reissue IEATDUMP.
- Ref: https://www.ibm.com/docs/en/zos/2.2.0?topic=xct-ieatdump-transaction-dump-request

2022-07-06 14:02 UTC, davidjmccann commented
@babsingh Would you be kind enough to kick off another zos test please?

2022-07-06 14:53 UTC, babsingh commented
jenkins build zos

2022-08-01 19:12 UTC, davidjmccann commented
@babsingh I've decided that running the test on z/OS probably isn't worth it, given that the paths don't really have the same meaning on that platform. The test is passing on Windows, Mac and Linux. Could you kick off a build on the other platforms if you're happy with that approach?

2022-08-04 14:12 UTC, babsingh commented
re https://github.com/eclipse/omr/pull/6532#issuecomment-1201604003:

The port library functions should work the same way on all supported platforms. The new test identifies a deficiency in `omrdump_create`'s functionality on zOS. Avoiding the test on zOS would correlate to ignoring the problem. So, I don't agree with disabling the test on zOS.

The correct approach would be to understand the problem in more depth. 
- One of the previous changes did correctly generate a core file on zOS: https://github.com/eclipse/omr/pull/6532#issuecomment-1157991424.
- When the core file is not generated, zOS issues a `return-code` and `reason-code`. Using this information, we can reissue the core-generation for our scenario as shown in https://github.com/eclipse/omr/pull/6532#issuecomment-1150024470.
- https://github.com/eclipse/omr/pull/6525 has not been merged yet. If #6525's commit is cherry-picked to this PR (temporarily), it will allow us to enable debugging diagnostics in PR builds for better understanding the problem.

2022-08-10 14:51 UTC, babsingh commented
**Incremental approach.** It will allow the PR to be merged without addressing the zOS issue.
- A detailed comment should be added above the test highlighting the zOS issue.
- A Github issue should be opened to track the zOS issue corresponding to the test.
After the PR is merged, the zOS issue can be handled in the future.

2022-08-12 15:53 UTC, davidjmccann commented
Thanks @babsingh. I've ammended both the commit comment, and above the test; is the comment sufficient? Once the pull request is approved I will raise an issue.

2022-08-12 16:30 UTC, babsingh commented
jenkins build all

2022-08-15 14:51 UTC, babsingh commented
jenkins build all

2022-08-15 15:43 UTC, babsingh commented
jenkins build zos

2022-08-17 14:01 UTC, babsingh commented
> https://ci.eclipse.org/omr/job/PullRequest-linux_ppc-64_le_gcc/3758/console

Known failure: https://github.com/eclipse/omr/issues/6571

> https://ci.eclipse.org/omr/job/PullRequest-linux_riscv64_cross/806/console

Known failure: https://github.com/eclipse/omr/issues/6665

2022-08-17 14:02 UTC, merged

2022-08-17 14:03 UTC, babsingh commented
re https://github.com/eclipse/omr/pull/6532#issuecomment-1213264095:

Can you open an OMR Github issue for the zOS challenges?

2022-08-17 17:32 UTC, davidjmccann commented
@babsingh I've created issue #6667 if you want to add any further comments.