Add test for cgroup subsystem iterator functions
eclipse/omr pull request #6559
Opened 2022-06-09 14:55 UTC by EricYangIBM

* Add testing for omrsysinfo_cgroup_subsystem_iterator_* functions; checks
a few key metrics and that iterating doesn't fail.
* Change default return value from OMRPORT_ERROR_SYSINFO_CGROUP_SUBSYSTEM_UNAVAILABLE
to OMRPORT_ERROR_SYSINFO_CGROUP_UNSUPPORTED_PLATFORM to keep consistency
between Unix and non-Unix.

Issue: https://github.com/eclipse/omr/issues/1281
Signed-off-by: Eric Yang <eric.yang@ibm.com>

2022-06-09 15:42 UTC, babsingh commented
> return OMRPORT_ERROR_SYSINFO_CGROUP_UNSUPPORTED_PLATFORM to be consistent with the other platforms?

Yes.

2022-06-10 18:07 UTC, EricYangIBM commented
This PR is ready for review

2022-06-14 16:36 UTC, babsingh commented
jenkins build all

2022-06-14 18:46 UTC, babsingh requested changes
- Test LGTM. PR builds pass. 
- Just the documentation of the `OMRPORT_ERROR_SYSINFO_CGROUP_UNSUPPORTED_PLATFORM` fix is missing in the commit message and PR description. It can even be a separate commit.

2022-06-14 19:00 UTC, babsingh commented
> https://ci.eclipse.org/omr/job/PullRequest-linux_ppc-64_le_gcc/3659/console

The `linux_ppc-64_le_gcc` failure is documented in https://github.com/eclipse/omr/issues/6556, and it is unrelated to this PR.

2022-06-14 19:15 UTC, babsingh commented
jenkins build all

2022-06-15 14:05 UTC, babsingh commented on fvtest/porttest/si.cpp
> +#if defined(LINUX)
Ref: https://github.com/eclipse/omr/pull/6567#discussion_r897117800
```suggestion
 #if defined(LINUX) && !defined(OMRZTPF)
```

2022-06-15 14:44 UTC, babsingh commented
jenkins build all

2022-06-15 19:22 UTC, babsingh commented
jenkins build linux_riscv64_cross

2022-06-15 19:29 UTC, babsingh approved these changes

2022-06-15 20:02 UTC, 0xdaryl commented
Jenkins build all

2022-06-15 20:55 UTC, 0xdaryl commented
Jenkins build win

2022-06-15 23:58 UTC, 0xdaryl approved these changes

2022-06-15 23:58 UTC, merged