RISC-V: add variant of instruction encoding utilities taking RegNum
eclipse/omr pull request #6578
Opened 2022-06-20 11:52 UTC by janvrany

These variants are useful when generating "hand-written" code such as snippets,
trampolines and thunks.

2022-06-20 12:46 UTC, janvrany commented
jenkins build riscv

2022-11-10 14:29 UTC, janvrany commented
jenkins build riscv

2022-11-10 17:42 UTC, janvrany commented
@0xdaryl , @mstoodle : may I kindly ask for review?

2023-02-01 14:14 UTC, 0xdaryl requested changes
Please update copyrights to 2023.

2023-02-01 14:14 UTC, 0xdaryl commented on compiler/riscv/codegen/RVInstructionUtils.hpp
> +#endif // RVINSTRUCTIONUTILS_INCL
Add newline.

2023-02-01 15:41 UTC, janvrany commented
jenkins build riscv

2023-02-01 20:12 UTC, janvrany commented
New version should have copyright fixed as well as newline. 
As for the failures, they seem to me unrelated - some port tests fail.

2023-02-01 21:59 UTC, 0xdaryl approved these changes

2023-02-01 21:59 UTC, 0xdaryl commented
This is a RISC-V specific change.  None of the other CI failures apply to this PR.  Merging.

2023-02-01 22:00 UTC, merged