Add options to control the costs of collecting thread stack traces
eclipse/omr pull request #6629
Opened 2022-07-28 14:58 UTC by keithc-ca

Allow separation of symbol resolution from collecting stack traces. Don't call `introspect_backtrace_symbols()` if `OMR_INTROSPECT_NO_SYMBOLS` is specified in `J9ThreadWalkState.options` given to `omrintrospect_threads_*()`.

Add `introspect_backtrace_symbols_ex()` which accepts options, the first of which, `OMR_BACKTRACE_SYMBOLS_BASIC`, controls the cost of symbol resolution. Currently, this is only meaningful on Linux where full symbol resolution can be costly.

2022-07-28 19:18 UTC, 0xdaryl commented
@babsingh : please review

2022-08-02 14:40 UTC, babsingh requested changes

2022-08-03 16:22 UTC, keithc-ca commented on include_core/omrport.h
> + */
The first comment introduces the list of options; the second describes the first (and only) option.
I'll add a blank line to separate them.

2022-08-03 16:23 UTC, keithc-ca commented on include_core/omrport.h
> + */
Same as above: one comment for the group of options, another for the first option.
I'll add a blank line here as well.

2022-08-03 16:29 UTC, keithc-ca commented on port/common/omrosbacktrace.c
> +		if (portLibrary->sig_protect(portLibrary, protectedIntrospectBacktraceThread, &args, handler, NULL, OMRPORT_SIG_FLAG_SIGALLSYNC | OMRPORT_SIG_FLAG_MAY_RETURN, &ret) != 0) {
A local variable cannot be used as suggested (this is C code), but I will split the split this call and move the constant to the left of `!=`.

2022-08-03 16:31 UTC, keithc-ca commented on port/common/omrosbacktrace.c
> +		if (portLibrary->sig_protect(portLibrary, protectedIntrospectBacktraceSymbols, &args, handler, NULL, OMRPORT_SIG_FLAG_SIGALLSYNC | OMRPORT_SIG_FLAG_MAY_RETURN, &ret) != 0) {
I will update this as above.

2022-08-03 16:34 UTC, keithc-ca commented on port/ztpf/omrosbacktrace_impl.c
> +		J9PlatformThread *threadInfo, J9Heap *heap, uint32_t options)
Good catch: fixed.

2022-08-03 16:42 UTC, keithc-ca commented on port/common/omrosbacktrace.c
> +/* Packaging struct to pass aguments through the signal protection. */
I should have noticed that myself; now fixed.

2022-08-03 16:43 UTC, keithc-ca commented
Updated based on review feedback.

2022-08-03 17:14 UTC, babsingh commented
jenkins build all

2022-08-03 18:02 UTC, keithc-ca commented
The last successful plinux PR build was on July 19; all have failed since so I don't think it has anything to do with this.

2022-08-03 18:34 UTC, babsingh commented
> https://ci.eclipse.org/omr/job/PullRequest-linux_ppc-64_le_gcc/3727/console

Yes, it is a known issue; unrelated to this PR. https://github.com/eclipse/omr/issues/6556 matches this failure.

2022-08-03 18:36 UTC, babsingh commented
Pinged @AdamBrousseau since all OMR zOS nodes are offline.

2022-08-03 18:37 UTC, babsingh approved these changes
LGTM; will merge once the zOS build passes.

2022-08-03 20:15 UTC, pshipton commented
The zOS build has passed now.

2022-08-03 20:16 UTC, merged