Add option for user space core dump on Linux
eclipse/omr pull request #6688
Opened 2022-09-02 13:50 UTC by mikezhang1234567890

Add an environment variable toggle to switch to creating a system core dump
manually in the current directory rather than rely on the kernel to create a
dump automatically from a signal and storing it where the OS dictates.

Fixes https://github.com/eclipse/omr/issues/6300 by providing an alternative to the kernel made system dump.

2022-09-13 17:33 UTC, mikezhang1234567890 commented
After discussion with @babsingh, we determined the following changes to improve this PR:

- Update comments to doxygen format
- use camel case for naming variables
- ensure all variables are initialized to a value
- use macros instead of integer constants
- update PR description with a high level overview describing how the core dump works
- use port library IO instead of native
- use flag to determine whether user space core dump should be used, instead of checking the environment
- set up testing, here or through OpenJ9 consuming this component

2022-09-13 17:50 UTC, babsingh commented
re https://github.com/eclipse/omr/pull/6688#issuecomment-1245726254:

The following points were missed:
- use a flag at startup instead of an environment variable; and
- do not introduce variables which contain `J9`.

The above feedback was verbally given on 7 Sept 22.

2022-09-13 17:52 UTC, babsingh commented
@mikezhang1234567890 Remove the draft state once the PR is ready for review. 

@keithc-ca For help with reviewing the PR once it is GTG.

2022-09-13 21:16 UTC, keithc-ca requested changes

2022-09-13 21:16 UTC, keithc-ca commented on port/linux/omrosdump_helpers.c
> +		if (bytes_read > 0) {
Perhaps the condition should be `sizeof(auxv_entry) == bytes_read`?

2022-09-13 21:16 UTC, keithc-ca commented on port/linux/omrosdump_helpers.c
> +	if (file_fd > 0) {
`file_fd >= 0`

2022-09-13 21:16 UTC, keithc-ca commented on port/linux/omrosdump_helpers.c
> +		else {
one line, please

2022-09-13 21:16 UTC, keithc-ca commented on port/linux/omrosdump_helpers.c
> +				local_buffer[index++] = ch;
Missing check that `index < sizeof(local_buffer)`.

2022-09-13 21:16 UTC, keithc-ca commented on port/linux/omrosdump_helpers.c
> +	snprintf(proc_filename + 6, 32 - 6, "%d/stat", ppid);
Same `/proc/` comment as before.

2022-09-13 21:16 UTC, keithc-ca commented on port/linux/omrosdump_helpers.c
> +	if (read_word_from_stat(proc_fd, read_buffer)) {
Explicit comparisons with zero.

2022-09-13 21:16 UTC, keithc-ca commented on port/linux/omrosdump_helpers.c
> +	char corename[8] = "CORE"; /* size 8 for alignment */
No alignment guarantee here.

2022-09-13 21:16 UTC, keithc-ca commented on port/linux/omrosdump_helpers.c
> +			for (i=0; i < 13; i++) {
space both sides of `=`

2022-09-13 21:16 UTC, keithc-ca commented on port/linux/omrosdump_helpers.c
> +	if(!write_note_auxv_data(outfile_fd, &file_off, &note_hdr.n_descsz)) {
space after `if`

2022-09-20 20:22 UTC, keithc-ca commented on port/unix/omrosdump.c
> +		if (getenv("J9_USER_DUMP")) {
`J9_USER_DUMP` might be a name that suits openj9, but other downstream projects would probably disagree.

2023-07-20 18:20 UTC, closed without merging