zTPF: Disable address range search on mmap failure
eclipse/omr pull request #6691
Opened 2022-09-05 15:13 UTC by jjohnst-us

The z/TPF OS does not support address range checking when an mmap request
fails.

[skip ci]

2022-09-12 20:35 UTC, jjohnst-us commented
@charliegracie 

Any comments on this PR?  The file is under the ztpf directory so shouldn't affect other platforms.

2022-09-26 15:20 UTC, babsingh commented
- What prevents z/TPF OS to not support address range checking? The ifdef'ed code invokes `default_pageSize_reserve_memory`. Why it stops working?
- Can you point me to the code where the mentioned mmap request fails?
- `port/ztpf/omrvmem.c` is only used for z/TPF. Why not just delete the ifdef'ed code?

2022-09-27 14:37 UTC, jjohnst-us commented
@babsingh 

Hi, thanks for taking a look.  The mmap for z/TPF architecture is very different than the standard community mmap.  This update has been in our systems for quite a while, so I don't recall exactly the issue.  I believe the issue is that for a given allocation request, we may always return NULL, and we are expecting to fail maybe because of a JVM misconfiguration, however, the address range search appears to assume it can eventually fufill the request, and I believe we end up going into an infinite loop.  Additionally, in our implementation I don't know if there is a benefit to address searching, is that to help with fragmentation?

With respects to just deleting code, instead of ifdef'ing code, I thought of that as well.  I think I leave it in there as convenience thinking we can use it for reference when we go to update the segment in the future (i.e., bug resolution).  However, I don't feel strongly about it, let me know if you want it removed.  Our hopes in the future is to standardize our mmap, but its currently not high on our priority list.

Yes, this has been in our system for a while.  We are just now getting around to submitting the code.

2022-09-27 15:27 UTC, babsingh requested changes

2022-09-27 15:27 UTC, babsingh commented on port/ztpf/omrvmem.c
> +#endif
https://github.com/eclipse/omr/blob/master/doc/CodingStandard.md#comment-conditional-compilation-directives-if-ifdef-ifndef-else-elif-endif
```suggestion
#endif /* OMRZTPF */
```

2022-09-27 15:27 UTC, babsingh commented on port/ztpf/omrvmem.c
> +#ifndef OMRZTPF
A comment should be added to highlight the key points from https://github.com/eclipse/omr/pull/6691#issuecomment-1259603661: mmap differences on z/TPF architecture, infinite loop issue and plans (TODOs) for the future.

2022-09-27 15:31 UTC, babsingh commented
> if there is a benefit to address searching, is that to help with fragmentation?

It's just the best effort approach to find memory.

> let me know if you want it removed

We can keep the code since there are plans to standardize mmap on z/TPF in the future. This code may work when the standardization occurs.

2022-09-27 20:49 UTC, jjohnst-us commented on port/ztpf/omrvmem.c
> +#endif
Done

2022-09-27 21:03 UTC, babsingh commented on port/ztpf/omrvmem.c
> + * z/TPF mmap support is updated.
Removed double space, added missing punctuation and minor rewording.
```suggestion
 * Disable address range search for z/TPF. Current z/TPF support for mmap
 * is non-standard. Due to the non standard behaviour, the address range
 * search may cause an infinite loop in some scenarios where mmap fails.
 * The address range search maybe re-enabled in the future once z/TPF
 * mmap support is updated.
```

2022-09-28 03:55 UTC, babsingh approved these changes
No PR builds required since OMR Jenkins does not have z/TPF machines.

2022-09-28 03:55 UTC, merged

2022-09-30 00:41 UTC, knn-k commented
This PR has changed the file mode, and I don't think that is intended.

```
mode change 100644 => 100755 port/ztpf/omrvmem.c
```

2022-09-30 16:21 UTC, babsingh commented
re https://github.com/eclipse/omr/pull/6691#issuecomment-1262975180: The intent was just to disable code, not change the file mode. Opened https://github.com/eclipse/omr/pull/6743 to revert the file mode to its original state.