Add execute flag for __moservice allocations on zOS
eclipse/omr pull request #6824
Opened 2022-11-21 21:41 UTC by joransiu

A new `__MOPL_EXECUTABLE` flag is being defined to the zOS LE `__moservices()` call to specify executable property under PTF UI83032. Explicitly set the execute storage flags for memory allocated with __moservices if appropriate.

2022-11-21 23:13 UTC, babsingh requested changes
The PR description has more details. The commit message does not match the PR description. Also, the commit message's body should be wrapped at 72 characters: https://github.com/eclipse/omr/blob/master/CONTRIBUTING.md#commit-guidelines.

2022-11-21 23:13 UTC, babsingh commented on port/zos390/omrvmem.c
> +#endif
Missing comment: https://github.com/eclipse/omr/blob/master/doc/CodingStandard.md#comment-conditional-compilation-directives-if-ifdef-ifndef-else-elif-endif
```suggestion
#endif /* __MOPL_EXECUTABLE */
```

2022-11-21 23:13 UTC, babsingh commented on port/zos390/omrvmem.c
> +	 * unless DIAGxx IARNONEXEC64 trap is set. The __MOPL_EXECUTABLE flag is ignored on systems that do not support the flag.
In the past, I was told not to exceed 100 chars in a single line for comments.

2022-11-21 23:13 UTC, babsingh commented on port/zos390/omrvmem.c
> +	if (OMR_ARE_ANY_BITS_SET(OMRPORT_VMEM_MEMORY_MODE_EXECUTE, params->mode)) {
The order of value and bits should be swapped as per the macro's definition:
https://github.com/eclipse/omr/blob/26e52210d25d5b3cd84b1573d4060ef7b663303e/include_core/omrcomp.h#L577
```suggestion
	if (OMR_ARE_ANY_BITS_SET(params->mode, OMRPORT_VMEM_MEMORY_MODE_EXECUTE)) {
```

2022-11-22 18:37 UTC, joransiu commented
Thanks for the quick feedback @babsingh!  I should have addressed all your concerns in c7f7958.  Thanks!

2022-11-22 19:14 UTC, babsingh commented
Thanks. Only the following feedback is pending: https://github.com/eclipse/omr/pull/6824#pullrequestreview-1189043489

> The PR description has more details. The commit message does not match the PR description. Also, the commit message's body should be wrapped at 72 characters: https://github.com/eclipse/omr/blob/master/CONTRIBUTING.md#commit-guidelines.

2022-11-22 20:52 UTC, joransiu commented
> Thanks. Only the following feedback is pending: [#6824 (review)](https://github.com/eclipse/omr/pull/6824#pullrequestreview-1189043489)
> 
> > The PR description has more details. The commit message does not match the PR description. Also, the commit message's body should be wrapped at 72 characters: https://github.com/eclipse/omr/blob/master/CONTRIBUTING.md#commit-guidelines.

Sorry, somehow missed that comment.  I've updated the commit message text.

2022-11-22 20:54 UTC, babsingh commented
jenkins build all

2022-11-22 21:44 UTC, babsingh commented
> https://ci.eclipse.org/omr/job/PullRequest-linux_ppc-64_le_gcc/3880/consoleFull

Known failure: https://github.com/eclipse/omr/issues/6571
```
16:07:26  30: [0;32m[----------] [m14 tests from Special/PPCDirectEncodingTest
16:07:26  30: free(): invalid next size (normal)
16:07:26  30/30 Test #30: compunittest ......................Child aborted***Exception:   0.89 sec
```

2022-11-22 21:45 UTC, babsingh approved these changes

2022-11-22 21:45 UTC, merged