Enable vbitselect IL opcode on PPC
eclipse/omr pull request #6832
Opened 2022-11-30 15:14 UTC by midronij

Enable `vbitselect` for all vector types. This, as well as https://github.com/eclipse-openj9/openj9/pull/16393 will allow the vectorization of blend() operations to occur.

2022-11-30 21:29 UTC, IBMJimmyk requested changes
Was there a reason this change is being done separately to the implementation of `vbitselectEvaluator`. I also checked the evaluator and it seems good to me so I was wondering why it wasn't enabled at the same time the evaluator code was checked in.

2022-11-30 21:29 UTC, IBMJimmyk commented on compiler/p/codegen/OMRCodeGenerator.cpp
> +            return false;
A bit unrelated but can you add this fix to `TR::vconv` as well? `TR::vconv` also needs a false path.

2022-11-30 22:18 UTC, gita-omr commented
> Was there a reason this change is being done separately to the implementation of `vbitselectEvaluator`. I also checked the evaluator and it seems good to me so I was wondering why it wasn't enabled at the same time the evaluator code was checked in.

I think  vbitselectEvaluator used to be called vselectEvaluator and that one existed long time ago. Then, we renamed it into vbitselect since we knew that that's how it will be used.

2022-12-01 21:11 UTC, vijaysun-omr approved these changes

2022-12-01 21:11 UTC, vijaysun-omr commented
Jenkins build all

2022-12-01 21:17 UTC, IBMJimmyk approved these changes
Looks good to me.

2022-12-01 21:19 UTC, gita-omr approved these changes

2022-12-01 22:11 UTC, merged