Verbose GC CRIU Support
eclipse/omr pull request #6850
Opened 2022-12-14 16:30 UTC by RSalman

Files opened by Verbose GC must be excluded from the CRIU dump. Opened logs can be problematic as the restore file validation can fail if the logs change between checkpoint and restore (e.g. file contents/metadata changed or file not available at restore time, which is typical for CRIU use cases). Hence, Verbose GC file writers/streams must be closed prior to creating a check point image and reopened for restore.

- Introduced `openStream` for Verbose Writers
  - Used to openFile associated with file writers , only required for buffered and  synchronous file logging, base class `MM_VerboseWriterFileLogging`
- Introduced `openStreams` for Verbose Manager
  - To walk the set of verbose writers and open streams  (complementary to existing `closeStreams` routine)
- Introduced `prepareForCheckpoint` and `reinitializeForRestore` for Verbose Manager
  - Calls Manager's Close/OpenStreams 

Signed-off-by: Salman Rana <salman.rana@ibm.com>

2022-12-14 16:31 UTC, RSalman commented
Please review @amicic @dmitripivkine 

cc @tajila

2022-12-14 17:51 UTC, RSalman commented
Reprinting the Initialized header and other verbose related CRIU work will be done in subsequent PRs. This only addresses the immediate issue with VerboseGC + CRIU.

2022-12-14 18:30 UTC, RSalman commented
>`openFile` routines updated to account for a for restore use cases. During restore, If a file to be opened already exists, verbose gc appends output rather than truncating the file first as is done for existing uses.

This seems like the correct approach to me, but I can also see verbose restore act as a fresh init (e.g truncate existing file and reinit params for rotation logs).

With the approach implemented, in a rotating log scenario, we would start from the same file opened at the time of checkpoint. For example, if we're rotating between 4 logs 
```
-Xverbosegclog:verbose.log,4,10 

verbose.log.001
verbose.log.002
verbose.log.003 <-- checkpoint/restore
verbose.log.004
```

and vgc is on log 3 at the time of checkpoint, then restore will cause it to start at 3 again and append to that. If at the time of restore, none of the logs are present it will still start at `verbose.log.003`

2022-12-19 14:46 UTC, amicic commented
> > `openFile` routines updated to account for a for restore use cases. During restore, If a file to be opened already exists, verbose gc appends output rather than truncating the file first as is done for existing uses.
> 
> This seems like the correct approach to me, but I can also see verbose restore act as a fresh init (e.g truncate existing file and reinit params for rotation logs).
> 
> With the approach implemented, in a rotating log scenario, we would start from the same file opened at the time of checkpoint. For example, if we're rotating between 4 logs
> 
> ```
> -Xverbosegclog:verbose.log,4,10 
> 
> verbose.log.001
> verbose.log.002
> verbose.log.003 <-- checkpoint/restore
> verbose.log.004
> ```
> 
> and vgc is on log 3 at the time of checkpoint, then restore will start at 3 again and append to that. If at the time of restore, none of the logs are present it will create log 3

What about the scenario, where VGC was enabled at checkpoint VM, but files were physically removed before  doing a restore.... will everything work as if VGC was never enabled, what will be the file index (in your example)?

2022-12-19 17:07 UTC, dmitripivkine commented
I think common behaviour would be GC verbose log has not been requested for snapshot creation but might be set up at restore. It means general expectation is GC verbose log after restore is brand new (initial reset), even it was requested for snapshot creation. Also it means GC verbose log options should be taken at restore. I think we should treat restore as a "new" JVM run from GC verbose log management point of view.
There is possibility when customer might specify options for snapshot as request to apply them for any restore run. If we want to support this case we need to verify compatibility and blend together options provided for snapshot and requested at restore. I am not sure we want this complexity for first cut.
@tajila What do you think?

2023-01-09 15:22 UTC, tajila commented
> I think common behaviour would be GC verbose log has not been requested for snapshot creation but might be set up at restore. It means general expectation is GC verbose log after restore is brand new (initial reset), even it was requested for snapshot creation. Also it means GC verbose log options should be taken at restore. I think we should treat restore as a "new" JVM run from GC verbose log management point of view.

From a user perspective I think the most useful data would be a verbose log that begins at restore. So agree with the comment above.

That being said we should also be compatible with modes where verbose is requested from start-up. In this case I think it should capture both snapshot and restore data. If there are issues with elapsed time related data point we have ways to correct that.

2023-01-17 17:43 UTC, RSalman commented
Discussed this with @amicic, we decided that both (checkpoint and restore) set of verbose logs around should be kept only if the user doesn't specify file name, in which case the file name will default to `verbosegc.%Y%m%d.%H%M%S.%pid.txt`, this file name should be regenerated for restore, hence 2 separate files. On the other hand, if the file name is set and the file is already present at restore time, we simply truncate and overwrite it, similar behaviour as starting JVM with old log around .

2023-01-17 17:47 UTC, RSalman commented
When we have the capability to set a separate set of options for restore, the user should be able to specify a new verbose file name, different from the one inited at checkpoint run. This would be another way to keep the both set of logs.

2023-01-17 17:53 UTC, RSalman commented
>set of verbose logs should be kept only if the user doesn't specify file name, in which case the file name will default to verbosegc.%Y%m%d.%H%M%S.%pid.txt, this file name should be regenerated for restore

This PR doesn't implement this, I'm deferring this work until and will revisit it when 

>we have the capability to set a separate set of options for restore, the user should be able to specify a new verbose file name, different from the one inited at checkpoint run

2023-01-17 19:38 UTC, amicic commented on gc/verbose/VerboseWriterFileLoggingBuffered.cpp
> - * Copyright (c) 1991, 2020 IBM Corp. and others
a few flies does not seem to be changed anymore after the last updates, so no need to change copyright year either

2023-01-17 21:36 UTC, amicic commented on gc/verbose/VerboseWriterFileLogging.cpp
> +	return openFile(env, true);
think about adding a comment what's the meaning of this 'true' and why we pass it

2023-01-17 21:37 UTC, amicic commented on gc/verbose/VerboseManagerBase.hpp
> +	virtual void prepareForCheckpoint(MM_EnvironmentBase *env) {};
semi-colon at the very end is not necessary

2023-01-17 21:40 UTC, amicic commented
looks good. approving, although a couple of minor comments should be addressed

2023-01-17 21:40 UTC, amicic approved these changes

2023-01-20 19:25 UTC, RSalman commented
Sorry, I missed the latest review comments, they've been addressed now.  

@babsingh could you please proceed with review/merge

2023-01-20 20:56 UTC, babsingh requested changes

2023-01-20 20:56 UTC, babsingh commented on gc/base/Configuration.hpp
> +	virtual void adjustGCThreadCountForCheckpoint(MM_EnvironmentBase* env) { adjustGCThreadCountOnCheckpoint(env); }
This line is too long (>100 chars); it should be spread across multiple lines:
```suggestion
	virtual void
	adjustGCThreadCountForCheckpoint(MM_EnvironmentBase* env)
	{
		adjustGCThreadCountOnCheckpoint(env);
	}
```

2023-01-21 00:16 UTC, RSalman commented
Please hold off on merging. Internal Axxon builds have a compile issue with these changes, looking into it.

2023-01-23 14:33 UTC, babsingh commented
jenkins build all

2023-01-23 14:40 UTC, babsingh commented
> https://dev.azure.com/eclipse-omr/omr/_build/results?buildId=7014&view=logs&j=aa2fd561-a338-5537-45ee-49ae22aea958&t=20ff6471-47a7-5631-6842-540dac3e3fb4

Known failure: https://github.com/eclipse/omr/issues/6516

2023-01-23 14:44 UTC, babsingh commented
re https://github.com/eclipse/omr/pull/6850#issuecomment-1400455931: @RSalman can you confirm that there are no other failures in the failed OSX PR build?

2023-01-23 16:40 UTC, RSalman commented
>re https://github.com/eclipse/omr/pull/6850#issuecomment-1400455931: @RSalman can you confirm that there are no other failures in the failed OSX PR build?

Yup, not seeing anything other than the known socket test:

```
2023-01-21T00:21:13.1470330Z 98% tests passed, 1 tests failed out of 47
2023-01-21T00:21:13.1471310Z 
2023-01-21T00:21:13.1472370Z Total Test time (real) = 220.19 sec
2023-01-21T00:21:13.1473060Z 
2023-01-21T00:21:13.1474650Z The following tests FAILED:
2023-01-21T00:21:13.1477050Z 	 32 - porttest (Failed)
```

2023-01-23 17:11 UTC, merged