Modify DLL search order
eclipse/omr pull request #6931
Opened 2023-03-21 16:44 UTC by dnakamura

Prioritize searching for dll dependencies in the same folder as the dll.

2023-03-21 18:03 UTC, dnakamura commented
See eclipse-openj9/openj9#15908

2023-03-21 18:54 UTC, babsingh requested changes

2023-03-21 18:54 UTC, babsingh commented on port/win32/omrsl.c
> +	 */
fixes typo, less than 100 chars per line and added a period.
```suggestion
	/* LoadLibraryExW will try appending .DLL if necessary.
	 * LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR causes the operating system to search for dependencies in the same folder. 
	 * This behaviour is similar to LOAD_WITH_ALTERED_SEARCH_PATH.
	 */
```

2023-03-21 18:54 UTC, babsingh commented on port/win32/omrsl.c
> +	/* LoadLibrary will try appending .DLL if necessary */
for consistency with the previous comment
```suggestion
	/* LoadLibrary will try appending .DLL if necessary. */
```

2023-03-21 20:16 UTC, babsingh commented
Line endings check fails:
```
###################################
port/win32/omrsl.c:170: trailing whitespace.
+	 * LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR causes the operating system to search for dependencies in the same folder. 
###################################
```

2023-03-23 19:10 UTC, babsingh commented
@AdamBrousseau Is there a win32 build to test these changes?

@dnakamura Have you tested these changes locally?

2023-03-23 19:48 UTC, dnakamura commented
> @dnakamura Have you tested these changes locally?

I ran an openj9 personal build against the changes.

2023-03-23 20:02 UTC, babsingh commented
There is no way to test the changes in the PR builds. @dnakamura Can you provide the link to the personal build? I will use it as a ref to merge this PR.

2023-03-23 20:09 UTC, babsingh commented
> There isn't currently, but it may be as easy as adding the build spec for it to [omrbuild.groovy](https://github.com/eclipse/omr/blob/master/buildenv/jenkins/omrbuild.groovy). Not sure.

Opened https://github.com/eclipse/omr/issues/6933 for feasibility analysis. Not sure if existing infra (machines + tooling) is sufficient or if all testing will pass.

2023-03-29 17:05 UTC, dnakamura commented
Could not find original build. ran a new one
https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/16075/

2023-03-29 18:01 UTC, babsingh approved these changes

2023-03-29 18:21 UTC, babsingh commented
After looking at the source code again, I found that there is only `win32/omrsl.c`. So, both win32 and win64 PR builds should also use this implementation.

2023-03-29 18:21 UTC, merged