GC CRIU: Reinit Scavenger Caches (Split CopyScanCacheList)
eclipse/omr pull request #6970
Opened 2023-04-27 17:33 UTC by RSalman

Scavenger cache lists must be reinitialized during restore (CRIU) according to the new GC thread count. Specifically, when the thread count is increased, it is necessary to divide the CopyScanCacheLists into smaller sublists. This is required to reduce contention on the cache lists (_scavengeCacheFreeList and
_scavengeCacheScanList) and ultimately improve GC performance for the restore environment. 

The following changes have been made:
- Reinit for each inited CopyScanCacheList (2 in total, owned by Scavenger)
  - Introduced reinitializeForRestore for Scavenger
  - Introduced reinitializeForRestore for CopyScanCacheList
- CopyScanCacheList must allocate a new array of sublists, copy over old sublists and init new sublists

For background, see X (Compensate for Thread Count Change)

2023-04-28 03:24 UTC, RSalman commented
@amicic please review

2023-05-01 15:57 UTC, amicic approved these changes

2023-05-01 16:04 UTC, RSalman commented
@babsingh this is ready for further review / merge

2023-05-01 17:18 UTC, babsingh requested changes

2023-05-02 04:03 UTC, babsingh requested changes

2023-05-02 13:37 UTC, babsingh commented
jenkins build all

2023-05-03 15:57 UTC, babsingh approved these changes

2023-05-03 15:57 UTC, merged