Correct SPDX license identifiers
eclipse/omr pull request #6996
Opened 2023-05-18 14:43 UTC by keithc-ca

Issue #6995:
* "GPL-2.0" should have been "GPL-2.0-only"
* "OpenJDK-assembly-exception-1.0" replaces "Assembly-exception"

2023-05-24 18:29 UTC, mstoodle requested changes
haven't checked everything yet, but the mentioned missing characters cause build breaks

2023-05-24 19:02 UTC, keithc-ca commented on jitbuilder/apigen/schema/api.schema.json
> +    "$comment": "SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0 OR GPL-2.0-only WITH OpenJDK-assembly-exception-1.0
Corrected in 62c1cd97089e589f0a2b440fd70929090753f153.

2023-05-24 20:22 UTC, mstoodle requested changes
even json file has the same issue of missing ", at the end of the line that's been updated (except the first one I pointed out which has been fixed - thanks!)

2023-05-24 20:22 UTC, mstoodle commented on jitbuilder/apigen/schema/api-class.schema.json
> +    "$comment": "SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0 OR GPL-2.0-only WITH OpenJDK-assembly-exception-1.0
same missing ", at end of line

2023-05-24 20:22 UTC, mstoodle commented on jitbuilder/apigen/schema/api-field.schema.json
> +    "$comment": "SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0 OR GPL-2.0-only WITH OpenJDK-assembly-exception-1.0
missing ",

2023-05-24 20:22 UTC, mstoodle commented on jitbuilder/apigen/schema/api-service.schema.json
> +    "$comment": "SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0 OR GPL-2.0-only WITH OpenJDK-assembly-exception-1.0
missing ",

2023-05-24 20:22 UTC, mstoodle commented on jitbuilder/apigen/schema/api-type.schema.json
> +    "$comment": "SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0 OR GPL-2.0-only WITH OpenJDK-assembly-exception-1.0
missing ",

2023-05-24 21:02 UTC, keithc-ca commented
Hopefully I've fixed all files in 0972f4a4e2f7436e1dd51bea8156979175804c81.

2023-05-25 18:59 UTC, keithc-ca commented
Besides the json files, there were others that didn't get (mechanically) updated properly. Marking as draft until those are corrected.

2023-05-25 19:53 UTC, keithc-ca commented
Rebased and updated:
* fix new files added recently
* fix `*.s` files where long lines are not permitted
* correct files where the license identifier expression spanned two or more lines
* fix strange "SPDX-L$(LIBJITBUILDERDIR)cense-Identifier"

2023-05-29 13:38 UTC, keithc-ca commented
Removed "fixes" comment; new files added by recent pull requests will need to be updated.

2023-05-29 14:37 UTC, mstoodle approved these changes
I found `doc/ValgrindMemcheckAPI.md` which does not have the right license string (only "SPDX-License-Identifier: EPL-2.0 OR Apache-2.0" which is, I think, our original identifier so has been missed for a long time :( ). We can handle it in this PR or under a separate one since it's a long standing mistake.

The failure on MacOS is not due to this change (another instance of #6516)

2023-05-29 14:39 UTC, mstoodle commented
jenkins build all

2023-05-29 14:45 UTC, keithc-ca commented
I left `doc/ValgrindMemcheckAPI.md` as it was. It didn't have any invalid identifiers discussed in the issue. If I recall correctly, there were other such files. If the license in those files should be updated, I think that should be handled separately.

2023-05-30 14:53 UTC, AdamBrousseau commented
jenkins buld riscv

2023-05-30 14:54 UTC, AdamBrousseau commented
jenkins build riscv

2023-06-08 17:06 UTC, keithc-ca commented
Is this waiting for additional committer approvals, or something else?

2023-06-19 16:26 UTC, merged