Invoke Scavenger Reinit during Global GC Reinit
eclipse/omr pull request #7032
Opened 2023-06-14 17:59 UTC by RSalman

Relates to https://github.com/eclipse-openj9/openj9/pull/17459#discussion_r1218353391

Signed-off-by: Salman Rana <salman.rana@ibm.com>

2023-06-14 17:59 UTC, RSalman commented
@amicic please review

2023-06-15 14:44 UTC, amicic commented on gc/base/standard/ParallelGlobalGC.cpp
> +	} else if (_extensions->scavengerEnabled && (NULL != _extensions->scavenger)) {
should be under 
#if defined(OMR_GC_MODRON_SCAVENGER)

2023-06-15 15:21 UTC, amicic approved these changes

2023-06-15 16:03 UTC, babsingh requested changes

2023-06-15 20:50 UTC, babsingh commented
> https://ci.eclipse.org/omr/job/PullRequest-linux_riscv64_cross/1157/consoleFull

This failure is unrelated to this PR. Also, seen in https://github.com/eclipse/omr/pull/7012#issuecomment-1593211361.

```
09:51:25  29/30 Test #29: comptest ..........................Child killed***Exception: 1710.09 sec
09:51:25  test 30
09:51:25        Start 30: compunittest
```

2023-06-15 20:51 UTC, babsingh approved these changes

2023-06-15 20:51 UTC, merged