x86: Remove deprecated TR_EnableNewX86PrefetchTLH
eclipse/omr pull request #7241
Opened 2024-01-24 17:30 UTC by BradleyWood

Issue: eclipse-openj9/openj9#9038

2024-01-24 17:30 UTC, BradleyWood commented
jenkins build all

2024-03-28 13:51 UTC, 0xdaryl requested changes

2024-03-28 13:51 UTC, 0xdaryl commented on compiler/runtime/Helpers.inc
>  SETVAL(TR_LXRH,TR_FSRH+37)
TR_FSRH+36

2024-04-02 13:21 UTC, BradleyWood commented
jenkins build all

@0xdaryl See [force-push](https://github.com/eclipse/omr/compare/9acbde2ab372b4ee5cc81b8ba774f97ff6788b26..e217fec6b35e4a9a4f81918f7a9e14a4673f7ea9)

2024-04-02 13:55 UTC, BradleyWood commented
macOS failure is #7181

2024-04-02 23:18 UTC, 0xdaryl approved these changes

2024-04-02 23:19 UTC, merged