x86: Update code-generator documentation
eclipse/omr pull request #7375
Opened 2024-06-12 19:12 UTC by BradleyWood

2024-07-26 02:06 UTC, 0xdaryl reviewed
Thanks for the contributions to the documentation.

2024-07-26 02:06 UTC, 0xdaryl commented on doc/compiler/x/OpCodeEncoding.md
> +To dynamically find the best encoding method you may call ```getSIMDEncoding(&cpu, vl)```.
Can you mention the class this function is a member of?

2024-07-26 02:06 UTC, 0xdaryl commented on doc/compiler/x/OpCodeEncoding.md
> +
Precede this with "For example," here if that's what it is.

2024-07-26 02:06 UTC, 0xdaryl commented on doc/compiler/x/OpCodeEncoding.md
> +To dynamically find the best encoding method you may call ```getSIMDEncoding(&cpu, vl)```.
Consider adding a permalink to where it is defined.

2024-08-20 19:08 UTC, BradleyWood commented on doc/compiler/x/OpCodeEncoding.md
> +To dynamically find the best encoding method you may call ```getSIMDEncoding(&cpu, vl)```.
No, doesn't matter when/where you call it

2024-08-20 19:10 UTC, BradleyWood commented
@0xdaryl See the [force-push](https://github.com/eclipse/omr/compare/0f0a05ab4a423d6a77f011bb1804506b01710ab2..546aa84349727a85630e0ace78f22d865f756b29)

2024-10-02 18:02 UTC, BradleyWood commented
@0xdaryl any update on this?

2024-10-03 16:20 UTC, 0xdaryl requested changes
Thanks for improving the documentation on these encodings--it is a good start.

Please de-hyphenate "code-generator" in the PR and commit titles.

One other minor typo nit to fix as well and this can be merged.

2024-10-03 16:20 UTC, 0xdaryl commented on doc/compiler/x/OpCodeEncoding.md
> +By not specifying an opcode encoding method, the code generator will use method specified
"...use the method..."

2024-10-03 19:36 UTC, BradleyWood commented
OK. @0xdaryl I updated the commit message, and that one mistake.

2024-10-03 19:45 UTC, 0xdaryl commented
Please fix the line ending reported error.

2024-10-03 21:23 UTC, BradleyWood commented
@0xdaryl Fixed line endings

2024-10-04 00:17 UTC, 0xdaryl approved these changes

2024-10-04 00:17 UTC, merged