Fix -Wshift-negative-value Open XL warning in OMRCodeGenerator.hpp
eclipse/omr pull request #7417
Opened 2024-07-18 15:28 UTC by Deigue

warning: shifting a negative signed value is undefined [-Wshift-negative-value]
return ((-1ll) << 31) - 1;}   // min 32bit signed integer minus 1

Changes here attempt to resolve this to a more correct approach.

@keithc-ca Not sure if we settled on something specific for this item, but creating a placeholder PR for it from what I had retained with and to continue discussions/suggestions here.

2024-07-18 17:23 UTC, keithc-ca requested changes

2024-07-18 17:23 UTC, keithc-ca commented on compiler/z/codegen/OMRCodeGenerator.hpp
> +   int64_t getLargestNegConstThatMustBeMaterialized() { return ((int64_t)~(~((uint64_t)0) << 31)) - 1;}
This doesn't yield the same value (we don't want two uses of `~`); and the comment should stay:
```c
   int64_t getLargestNegConstThatMustBeMaterialized() { return (int64_t)(((~(uint64_t)0) << 31) - 1); } // min 32-bit signed integer minus 1
```

2024-08-02 17:02 UTC, keithc-ca approved these changes

2024-09-17 14:16 UTC, babsingh commented
jenkins build all

2024-09-17 21:55 UTC, babsingh approved these changes

2024-09-17 21:56 UTC, merged